CREATE TABLE IF NOT EXISTS db_dainam (
    `page` VARCHAR(22) CHARACTER SET utf8,
    `keyword` VARCHAR(93) CHARACTER SET utf8,
    `b` INT
);
INSERT INTO db_dainam VALUES
    ('3','A, Á, À, Ả, Ác  ',1),
    ('4','Ác, Ạc, Ách, Ạch, Ai  ',1),
    ('5','Ai, Ái, Ải, Áy, Ấy, Ậy  ',1),
    ('6','Am, Ám, Am, Ãm, Am  ',1),
    ('7','Âm, Ấm, Ấm  ',1),
    ('8','Ấm, Am, An, An, Án',1),
    ('9','An, Án, Ăn  ',1),
    ('10','Ăn  ',1),
    ('11','Ăn  ',1),
    ('12','Ăn, Ân, An, Ấn, Ẩn  ',1),
    ('13','Ẩn, Ang, Áng, Ảng, Anh  ',1),
    ('14','Anh, Ánh, Ảnh, Ao, Ạo, Áo  ',1),
    ('15','Áo, Ào, Áp, Ắp, Ấp  ',1),
    ('16','Ấp, Ập, Át, Ắt, Au, Ảu, Âu, Ấu, Ẩu',1),
    ('17','B, Ba, Bạ  ',1),
    ('18','Bạ, Bá  ',1),
    ('19','Bà, Bả  ',1),
    ('20','Bã, Bác, Bạc  ',1),
    ('21','Bạc, Bắc, Bác, Bấc  ',1),
    ('22','Bấc, Bậc, Bách, Bạch',1),
    ('23','Bạch, Bai, Bại, Bái',1),
    ('24','Bái, Bài, Bải',1),
    ('25','Bải, Bãi, Bay, Bày, Bảy',1),
    ('26','Bảy, Bây, Bậy, Bây, Bầy, Bẩy',1),
    ('27','Bàm, Bãm, Bạm, Bặm, Bẩm, Bâm, Bậm, Bấm, Bầm, Bẩm',1),
    ('28','Bẩm, Ban',1),
    ('29','Ban, Bạn, Bán',1),
    ('30','Bán, Bàn',1),
    ('31','Bàn, Bản, Băn, Bặn, Bấn, Bẩn, Bận, Bân',1),
    ('32','Bân, Bần, Bẩn, Bang, Bạng, Báng',1),
    ('33','Bàng, Bảng, Bãng, Băng',1),
    ('34','Băng, Bằng, Bãng, Bâng',1),
    ('35','Bâng, Bấng, Bậng, Bầng, Bẩng, Banh, Bánh',1),
    ('36','Bánh, Bành, Bảnh, Bao',1),
    ('37','Bao, Bạo, Báo',1),
    ('38','Báo, Bào, Bảo, Bão',1),
    ('39','Bão, Bạp, Báp, Bặp, Bập, Bát',1),
    ('40','Bát, Bạt, Bát',1),
    ('41','Bát, Bặt, Bất',1),
    ('42','Bất, Bật, Bạu, Bau, Bàu',1),
    ('43','Bàu, Bàu, Bau, Bậu, Bau, Bấu, Bẩu, Be, Bẹ',1),
    ('44','Bẹ, Bé, Bè, Bẻ, Bê, Bệ',1),
    ('45','Bệ, Bê, Bế, Bề, Bể',1),
    ('46','Bể, Bể, Bễ, Ben, Bén, Bèn, Bẹn, Bên, Bện, Bến',1),
    ('47','Bến, Bền, Bệnh',1),
    ('48','Bệnh, Beo, Bẹo, Béo, Bèo, Bẻo',1),
    ('49','Bẻo, Bếp, Bệp, Bép, Bẹp, Bét, Bẹt, Bết, Bệt',1),
    ('50','Bệt, Bêu, Bệu, Bều, Bi, Bị',1),
    ('51','Bị, Bí, Bì',1),
    ('52','Bì, Bỉ, Bia, Bìa, Bịch, Bích',1),
    ('53','Bích, Biếc, Biếm, Biên, Biện',1),
    ('54','Biện, Biến, Biền, Biển',1),
    ('55','Biển, Biêng, Biệng, Biếng, Biết',1),
    ('56','Biệt, Biệt, Biêu, Biếu',1),
    ('57','Biểu, Bìm, Bình',1),
    ('58','Binh, Bịnh, Bính, Bình',1),
    ('59','Bình, Bỉnh, Bịp, Bít, Bịt',1),
    ('60','Bịt, Biú, Bo, Bọ, Bó, Bò',1),
    ('61','Bò, Bỏ',1),
    ('62','Bỏ, Bõ, Bô, Bộ',1),
    ('63','Bộ, Bộ',1),
    ('64','Bồ',1),
    ('65','Bồ, Bổ, Bơ, Bợ, Bớ, Bờ, Bở',1),
    ('66','Bở, Bỡ, Bọc, Bóc, Bốc, Bộc, Bói',1),
    ('67','Bòi, Bôi, Bội, Bối, Bồi',1),
    ('68','Bồi, Bổi, Bơi, Bới, Bởi, Bỡi, Bom, Bôm, Bơm, Bợm',1),
    ('69','Bợm, Bởm, Bớm, Bon, Bọn, Bón, Bòn, Bỏn, Bôn',1),
    ('70','Bôn, Bộn, Bốn, Bồn, Bổn',1),
    ('71','Bỗn, Bơn, Bợn, Bớn, Bởn, Bờn, Bong, Bọng, Bóng',1),
    ('72','Bóng, Bòng, Bỏng, Bông',1),
    ('73','Bông, Bộng, Bống, Bồng, Bổng',1),
    ('74','Bổng, Bỗng, Bóp, Bọp, Bốp, Bộp, Bớp, Bợp, Bọt',1),
    ('75','Bọt, Bột, Bợt',1),
    ('76','Bợu, Bu, Bú, Bưa, Búa, Bủa',1),
    ('77','Bui, Bụi, Búi, Bùi, Bủi, Bụm, Bủm, Bun, Bún, Bùn, Bủn',1),
    ('78','Bủn, Bung, Bụng',1),
    ('79','Bụng, Búng, Bùng, Bủng, Buộc, Buôi',1),
    ('80','Buổi, Buồm, Buôn, Buồn',1),
    ('81','Buồn, Buông, Buồng, Búp, Bụp, Bút, Bụt',1),
    ('82','Bụt, Bư, Bứ, Bự, Bưa, Bựa, Bứa, Bừa, Bửa, Bữa',1),
    ('83','Bữa, Bức, Bực, Bưn, Bứng, Bựng, Bừng, Bửng, Bước, Bươi',1),
    ('84','Bươi-bươi, Bưởi, Bướm, Bươn, Bướn, Bườn, Bướu, Bứt, Bửu',1),
    ('85','Bửu, C, Ca, Cạ, Cá',1),
    ('86','Cá, Cà',1),
    ('87','Cà, Cả',1),
    ('88','Cả, Các, Cạc, Cặc, Cách',1),
    ('89','Cách, Cạch, Cai, Cái',1),
    ('90','Cái, Cài, Cải, Cãi, Cay',1),
    ('91','Cay, Cạy, Cáy, Cày, Cảy, Cây',1),
    ('92','Cây, Cậy, Cây, Cầy, Cam',1),
    ('93','Cam, Cám, Cảm, Căm, Cấm/Cặm',1),
    ('94','Cấm, Cằm, Câm, Cấm, Cầm',1),
    ('95','Cầm, Cầm, Cẩm',1),
    ('96','Cẩm, Can, Cạn, Cán',1),
    ('97','Cán, Càn, Cản, Căn, Cặn',1),
    ('98','Cặn, Cắn, Cần, Cân, Cân',1),
    ('99','Cân, Cận, Cấn, Cân, Cần',1),
    ('100','Cẩn, Cang, Cáng',1),
    ('101','Càng, Cảng, Căng, Cảng, Cãng, Câng, Canh',1),
    ('102','Canh, Cạnh',1),
    ('103','Cánh, Cảnh, Cao',1),
    ('104','Cao, Cạo, Cáo',1),
    ('105','Cáo, Cào, Cảo, Cáp, Cạp, Cáp',1),
    ('106','Cặp, Cấp, Cập',1),
    ('107','Cập, Cát, Cặt, Cất',1),
    ('108','Cất, Cật, Cau',1),
    ('109','Cau, Cảu, Cáu, Càu, Câu',1),
    ('110','Câu, Cậu, Cấu, Cầu',1),
    ('111','Cầu, Cầu',1),
    ('112','Cầu, Cẩu, Cha, Chạ',1),
    ('113','Chà, Chả, Chã, Chả, Chác, Chạc, Chác',1),
    ('114','Chác, Chạch, Chách, Chai, Chái, Chài',1),
    ('115','Chài, Chải, Chay, Chạy',1),
    ('116','Chạy, Cháy, Chày, Chảy, Chậy',1),
    ('117','Chậy, Chấy, Chày, Cham, Chạm, Chám, Chàm, Chăm, Chăm(Chàm)',1),
    ('118','Chăm, Chặm, Chăm, Chàm, Chằm, Chảm, Châm, Chậm',1),
    ('119','Chậm, Chấm, Chầm, Chẩm, Chan, Chạn',1),
    ('120','Chạn, Chán, Chăn, Chàn, Chãn, Chận',1),
    ('121','Chấn, Chần, Chẩn, Chang, Chạng, Cháng',1),
    ('122','Chàng, Chảng, Chạng, Chầng, Chảng',1),
    ('123','Chảng, Chấng, Chanh, Chạnh, Chánh',1),
    ('124','Chánh, Chành, Chảnh, Chao, Chạo, Cháo, Chào, Chảo',1),
    ('125','Chảo, Chạp, Cháp, Chạp, Chấp, Chát, Chạt',1),
    ('126','Chát, Chặt, Chất, Chật, Chau, Cháu',1),
    ('127','Cháu, Chảu, Châu, Chậu, Chấu',1),
    ('128','Chấu, Chầu, Che, Ché, Chè',1),
    ('129','Chè, Chẻ, Chẽ, Chê, Chế',1),
    ('130','Chế, Chề, Chệc, Chếch, Chém, Chẻm, Chêm, Chen',1),
    ('131','Chẹn, Chén, Chèn, Chẻn, Chênh, Chếnh, Cheo',1),
    ('132','Chéo, Chèo, Chẹo, Chẽo, Chép',1),
    ('133','Chép, Chẹp, Chệp, Chét, Chẹt, Chết',1),
    ('134','Chết, Chi',1),
    ('135','Chi, Chị, Chí',1),
    ('136','Chí, Chì, Chỉ',1),
    ('137','Chỉ',1),
    ('138','Chỉ, Chia, Chì, Chỉa, Chịa, Chích',1),
    ('139','Chích, Chiếc, Chiêm, Chiếm, Chiên',1),
    ('140','Chiên, Chiến, Chiêng, Chiệng, Chiếng, Chiết',1),
    ('141','Chiệt, Chiêu, Chiếu',1),
    ('142','Chiếu, Chiều, Chim, Chím, Chỉm, Chín',1),
    ('143','Chín, Chỉn, Chinh, Chính, Chỉnh',1),
    ('144','Chình, Chỉnh, Chĩnh, Chíp, Chít, Chịt, Chiu, Chịu',1),
    ('145','Chịu, Chìu',1),
    ('146','Chìu, Cho, Chó',1),
    ('147','Chó, Chỏ, Chõ, Chò, Chỗ',1),
    ('148','Chỗ, Chộ, Chồ, Chơ, Chợ, Chớ, Chờ',1),
    ('149','Chờ, Chở, Chỡ, Chóa, Chỏa, Choác, Choạc, Choai, Choại, Choái, Choán, Choản',1),
    ('150','Choàng, Choãnh, Choắt, Chóc, Chọc, Chốc, Choi, Chọi',1),
    ('151','Chọi, Chói, Chòi, Chõi, Chôi, Chối, Chồi, Chỏi',1),
    ('152','Chỏi, Chổi, Chơi, Chới, Chời, Chòm, Chỏm, Chôm',1),
    ('153','Chổm, Chơm, Chờm, Chởm, Chớm, Chọn, Chón, Chỏn, Chôn, Chốn, Chồn',1),
    ('154','Chồn, Chơn',1),
    ('155','Chơn, Chớn, Chờn, Chong, Chóng, Chòng, Chỏng, Chõng, Chông',1),
    ('156','Chông, Chống, Chồng, Chổng, Chóp',1),
    ('157','Chớp, Chợp, Chót, Chọt, Chốt, Chột, Chớt, Chợt, Chu',1),
    ('158','Chu, Chú, Chù, Chủ',1),
    ('159','Chủ, Chư, Chừ, Chử, Chữ, Chua',1),
    ('160','Chua, Chúa, Chùa, Chưa, Chứa',1),
    ('161','Chứa, Chừa, Chửa, Chữa, Chuẩn, Chúc',1),
    ('162','Chúc, Chục, Chức, Chự, Chuè, Chuẻ',1),
    ('163','Chuẻ, Chué, Chuen, Chuẻn, Chui, Chúi, Chùi, Chủi, Chuyên, Chuyện',1),
    ('164','Chuyện, Chuyến, Chuyền, Chuyển, Chum, Chụm, Chủm',1),
    ('165','Chủm, Chúm, Chùm, Chun, Chũn, Chưn, Chung',1),
    ('166','Chung, Chúng, Chùng, Chủng, Chưng',1),
    ('167','Chưng, Chứng, Chừng',1),
    ('168','Chừng, Chựng, Chửng, Chuốc, Chuộc, Chước',1),
    ('169','Chước, Chuôi, Chuối',1),
    ('170','Chuổi, Chuỗi, Chưởi, Chuòm, Chuốm, Chuồn, Chuông, Chuộng',1),
    ('171','Chuộng, Chương, Chướng, Chưởng',1),
    ('172','Chưởng, Chuốt, Chuột, Chụp, Chút, Chụt',1),
    ('173','Co, Cọ, Có',1),
    ('174','Có',1),
    ('175','Có, Cò, Cỏ, Cô',1),
    ('176','Cộ, Cô, Cố',1),
    ('177','Cố, Cổ, Cổ',1),
    ('178','Cổ, Cở, Cỡ, Cổ, Cơ',1),
    ('179','Cơ, Cớ',1),
    ('180','Cớ, Cờ',1),
    ('181','Cỡ, Cóc, Cọc, Cốc',1),
    ('182','Cốc, Cộc, Coi, Còi, Cỏi, Cõi',1),
    ('183','Cõi, Côi, Cội, Cối, Cồi, Cổi, Cơi, Cới, Cời',1),
    ('184','Cỡi, Còm, Côm, Cộm, Cốm, Cơm',1),
    ('185','Cơm, Cợm, Con',1),
    ('186','Con, Cón, Còn',1),
    ('187','Còn, Côn, Cồn, Cổn, Cơn',1),
    ('188','Cơn, Cợn, Cởn, Cong, Cọng, Cóng, Còng, Cỏng, Cõng, Công',1),
    ('189','Công',1),
    ('190','Công',1),
    ('191','Công, Cống, Cộng, Cồng, Cổng, Cọp, Cóp, Cớp, Cộp',1),
    ('192','Cợp, Cót, Cọt, Cốt, Cột',1),
    ('193','Cột, Cợt, Cu, Cụ, Cú',1),
    ('194','Cú, Cù, Củ',1),
    ('195','Củ, Củ, Cũ, Cư, Cự',1),
    ('196','Cự, Cứ, Cừ, Cử',1),
    ('197','Cử, Cữ, Cua, Của',1),
    ('198','Của, Cưa',1),
    ('199','Cưa, Cựa, Cứa, Cữa',1),
    ('200','Cữa, Cúc, Cục',1),
    ('201','Cực, Cức, Cui, Cụi, Cúi, Cùi',1),
    ('202','Cùi, Củi, Cũi',1),
    ('203','Củi, Cụm, Cúm, Cùm, Củm, Cùn, Củn, Cung',1),
    ('204','Cung, Cụng, Cúng',1),
    ('205','Cúng, Cùng, Cũng',1),
    ('206','Cũng, Cứng, Cửng, Cuốc, Cuộc',1),
    ('207','Cuộc, Cước, Cuội, Cuối, Cưới, Cười',1),
    ('208','Cười, Cườm, Cuộn, Cuốn',1),
    ('209','Cuốn, Cuông, Cuổng, Cương, Cường, Cượng',1),
    ('210','Cướng, Cưởng, Cướp, Cúp, Cút, Cụt, Cứt',1),
    ('211','Cứt, Cưu, Cứu, Cừu, Cửu',1),
    ('212','Cửu, D, Da',1),
    ('213','Da, Dạ',1),
    ('214','Dá, Dà, Dã, Dác, Dạc, Dặc',1),
    ('215','Dách, Dạch, Dai, Dại, Dái',1),
    ('216','Dài, Dải, Dãi, Day, Dạy',1),
    ('217','Dạy, Dáy, Dày, Dảy, Dãy, Dây',1),
    ('218','Dây, Dậy, Dấy, Dầy, Dảy, Dám, Dàm, Dặm',1),
    ('219','Dặm, Dằm, Dâm, Dậm, Dầm, Dan',1),
    ('220','Dan, Dán, Dạn, Dàn, Dặn',1),
    ('221','Dặn, Dân, Dận, Dấn, Dần',1),
    ('222','Dần, Dẫn, Dang, Dạng, Dáng, Dàng, Dặng, Dắng',1),
    ('223','Dằng, Dãng, Dâng, Dậng, Danh, Dành',1),
    ('224','Dành, Dao, Dạo, Dáo',1),
    ('225','Dào, Dão, Dáp, Dấp, Dập, Dát, Dạt, Dặt, Dật',1),
    ('226','Dáu, Dàu, Dâu, Dậu, Dấu',1),
    ('227','Dấu, Dầu, Dẫu, Dè, Dẽ',1),
    ('228','Dẽ, Dê, Dệ, Dế, Dề, Dể, Dễ',1),
    ('229','Dễ, Dém, Dẻm, Dện, Dẹo, Dèo, Dẻo, Dép',1),
    ('230','Dép, Dẹp, Dệt, Dêu, Dệu, Dều, Di',1),
    ('231','Di, Dị, Dì, Dỉ',1),
    ('232 Dỉ, Dìa, Dĩa, Dịch',NULL,1),
    ('233','Dịch, Diệc, Diêm, Diệm, Diềm, Diếm, Diên',1),
    ('234','Diện, Diễn, Diềng, Diếp, Diệp, Diệt, Diêu',1),
    ('235','Diêu, Diêu, Diệu, Diểu, Diều, Diễu, Dim, Din, Dín, Dinh',1),
    ('236','Dinh, Dịnh, Dính, Dịp, Dịu, Díu, Dìu, Do',1),
    ('237','Do, Dọ, Dó, Dò, Dỏ, Dồ, Dổ, Dỗ',1),
    ('238','Dỗ, Dơ, Dở, Dỡ, Dóa, Dọa, Doan',1),
    ('239','Doan, Doãn, Dọc, Dóc, Dộc, Doi, Dọi, Dói',1),
    ('240','Dỏi, Dõi, Dội, Dối, Dồi, Dơi, Dời',1),
    ('241','Dới, Dom, Dòm, Don, Dọn, Dón, Dõn, Dộn, Dồn',1),
    ('242','Dồn, Dợn, Dớn, Dờn, Dởn, Dong',1),
    ('243','Dong, Dọng, Dòng, Dõng, Dông, Dộng',1),
    ('244','Dộng, Dỗng, Dợp, Dót, Dốt, Dột, Du',1),
    ('245','Du, Dụ, Dù, Dủ, Dư',1),
    ('246','Dư, Dự, Dứ, Dừ, Dữ, Dua, Dùa, Dưa',1),
    ('247','Dưa, Dứa, Dựa, Dừa, Dục',1),
    ('248','Dục, Dức, Dực, Dệ, Duệ, Dụi, Dùi, Dũi, Duyên',1),
    ('249','Duyệt, Dum, Dũm, Dun, Dún, Dùn, Dung, Dụng',1),
    ('250','Dụng, Dùng, Dưng, Dựng, Dừng, Dửng',1),
    ('251','Dước, Dược, Duôi, Duối, Duỗi, Dượi, Dưới, Duơn',1),
    ('252','Duơn, Duông, Dương',1);
INSERT INTO db_dainam VALUES
    ('253','Dương, Dường, Dưỡng',1),
    ('254','Dưỡng, Duột, Dượt, Dụt, Dựt, Dứt',1),
    ('255','Đ, Đa, Đá',1),
    ('256','Đá, Đà, Đả',1),
    ('257','Đã, Đác, Đạc, Đắc, Đặc',1),
    ('258','Đặc, Đai, Đại',1),
    ('259','Đại, Đái, Đài',1),
    ('260','Đài, Đãi, Đay, Đáy, Đảy',1),
    ('261','Đảy, Đãy, Đây, Đậy, Đấy, Đầy',1),
    ('262','Đầy, Đẩy, Đẫy, Đam, Đạm, Đám, Đàm',1),
    ('263','Đàm, Đảm, Đãm, Đăm, Đắm, Đâm',1),
    ('264','Đậm, Đấm, Đầm, Đẫm, Đan, Đán, Đạn, Đàn',1),
    ('265','Đàn, Đãn, Đán, Đần, Đận, Đẩn, Đang, Đáng',1),
    ('266','Đáng, Đàng',1),
    ('267','Đàng',1),
    ('268','Đàng, Đảng, Đăng',1),
    ('269','Đăng, Đặng, Đắng',1),
    ('270','Đằng, Đẳng, Đâng, Đậng, Đấng, Đầng, Đanh, Đạnh, Đánh',1),
    ('271','Đánh',1),
    ('272','Đánh, Đành, Đảnh',1),
    ('273','Đảnh, Đao, Đạo',1),
    ('274','Đạo',1),
    ('275','Đạo, Đáo, Đào',1),
    ('276','Đào, Đảo',1),
    ('277','Đáp, Đạp, Đáp',1),
    ('278','Đáp, Đập, Đát, Đạt, Đắt, Đặt',1),
    ('279','Đặt, Đất',1),
    ('280','Đất, Đật, Đau, Đáu, Đàu, Đâu',1),
    ('281','Đâu, Đậu',1),
    ('282','Đậu, Đấu, Đầu',1),
    ('283','Đầu, Đẩu',1),
    ('284','Đẩu, Đe, Đé, Đè, Đẻ, Đê, Đệ',1),
    ('285','Đệ, Đế, Đề',1),
    ('286','Đề , Đễ',1),
    ('287','Để, Đem, Đém, Đêm, Đệm, Đếm',1),
    ('288','Đen, Đẹn, Đén, Đèn',1),
    ('289','Đèn, Đẻn, Đến, Đền',1),
    ('290','Đền, Đênh, Đeo, Đéo, Đèo, Đẻo, Đẽo, Đẹp',1),
    ('291','Đép, Đét, Đẹt, Đều, Đi',1),
    ('292','Đi, Đì, Đĩ',1),
    ('293','Địa, Đìa, Đỉa',1),
    ('294','Đỉa, Đích, Địch, Điếc, Điếm',1),
    ('295','Điếm, Điệm, Điềm, Điểm, Điên',1),
    ('296','Điên, Điện, Điền',1),
    ('297','Điền, Điển, Điếng, Điệp',1),
    ('298','Điệp, Điệt, Điêu, Điệu, Điếu',1),
    ('299','Điếu, Điểu, Điều, Điểu, Đinh',1),
    ('300','Đinh, Định, Đính, Đình',1),
    ('301','Đình, Đỉnh, Đít, Địt, Điu',1),
    ('302','Điu, Đíu, Đo, Đọ, Đó, Đò',1),
    ('303','Đò, Đỏ, Đô, Độ',1),
    ('304','Độ, Đố, Đồ',1),
    ('305','Đồ',1),
    ('306','Đồ, Đổ',1),
    ('307','Đổ, Đơ, Đợ, Đớ, Đờ, Đỡ',1),
    ('308','Đỡ, Đọa, Đóa, Đoác, Đoái',1),
    ('309','Đoài, Đoan, Đoạn, Đoán',1),
    ('310','Đoán, Đoàn, Đoản, Đoanh, Đoạt, Đọc',1),
    ('311','Đọc, Đóc, Đốc, Độc',1),
    ('312','Độc, Đoi, Đọi, Đói, Đòi',1),
    ('313','Đòi, Đỏi, Đôi, Đội',1),
    ('314','Đội, Đối, Đồi, Đỗi',1),
    ('315','Đỗi, Đợi, Đời',1),
    ('316','Đời, Đom, Đóm, Đốm, Đơm, Đờm, Đớm, Đỡm, Đon, Đọn, Đón, Đòn',1),
    ('317','Đòn, Đôn, Độn, Đốn, Đồn',1),
    ('318','Đồn, Đơn',1),
    ('319','Đơn, Đờn, Đớn, Đong, Đọng, Đóng',1),
    ('320','Đóng, Đòng, Đỏng',1),
    ('321','Đông',1),
    ('322','Đông, Động, Đống',1),
    ('323','Đồng',1),
    ('324','Đồng',1),
    ('325','Đồng, Đót, Đọt, Đốt',1),
    ('326','Đốt, Đột, Đợt, Đớt, Đu',1),
    ('327','Đú, Đụ, Đủ, Đù, Đư, Đừ, Đua',1),
    ('328','Đua, Đùa, Đũa, Đưa',1),
    ('329','Đưa, Đứa, Đừa, Đúc, Đục',1),
    ('330','Đục, Đức, Đực',1),
    ('331','Đực, Đui, Đùi, Đũi, Đụi, Đúm, Đùm, Đun, Đún, Đụn',1),
    ('332','Đũn, Đụng, Đúng, Đùng, Đủng, Đưng, Đựng, Đứng',1),
    ('333','Đứng, Đừng, Đững, Đuốc, Đước, Được',1),
    ('334','Được, Đuôi, Đuối',1),
    ('335','Đuổi, Đuồm, Đượm, Đuổn, Đượn, Đuông, Đương, Đượng, Đường, Đưởng',1),
    ('336','Đường, Đuột, Đút, Đụt, Đứt',1),
    ('337','E, É, Ẽ, È, Ê, Ế, Ễ, Ếc, Em',1),
    ('338','Em, Ém, Êm, Ếm, En, Én, Ễn, Ện, Eo',1),
    ('339','Eo, Éo, Ẻo, Ẹo, Ép, Ẹp, Ét, Gá, Gà',1),
    ('340','Gà, Gả, Gã',1),
    ('341','Gã, Gác, Gạc, Gặc, Gạch',1),
    ('342','Gạch, Gai, Gái, Gài',1),
    ('343','Gài, Gãi, Gay, Gạy, Gáy, Gảy, Gãy',1),
    ('344','Gãy, Gây, Gậy, Gầy, Găm, Gặm',1),
    ('345','Gặm, Gám, Gàm, Gãm, Gầm, Gẫm, Gan',1),
    ('346','Gan, Gạn, Gắn, Gằn, Gần',1),
    ('347','Gần, Gang, Gàng, Găng, Gáng, Gầng, Ganh, Gạnh, Gảnh',1),
    ('348','Gánh, Gành, Gao, Gạo',1),
    ('349','Gáo, Gáp, Gặp, Gấp, Gập, Gạt',1),
    ('350','Gát, Gặt, Gật, Gâu, Gấu, Ghe',1),
    ('351','Ghe, Ghẹ, Ghé, Ghè',1),
    ('352','Ghè, Ghẻ, Ghẽ, Ghê, Ghế, Ghếch, Ghém',1),
    ('353','Ghém, Ghen, Ghèn, Ghềnh, Gheo, Ghẹo, Ghép, Ghét, Ghi, Ghì, Ghiếc',1),
    ('354','Ghiền, Ghim, Ghình, Ghĩnh, Gi, Gí, Gì, Gỉ, Gia',1),
    ('355','Gia',1),
    ('356','Gia, Gịa, Giá',1),
    ('357','Giá',1),
    ('358','Giá, Già, Giả',1),
    ('359','Giả, Giã, Giác',1),
    ('360','Giác, Giạc, Giặc, Giấc, Giai, Giại',1),
    ('361','Giại, Giái, Giải',1),
    ('362','Giải, Giãi, Giay, Giạy, Giáy, Giày',1),
    ('363','Giày, Giãy, Giây, Giấy',1),
    ('364','Giầy, Giẫy, Giam, Giám, Giảm',1),
    ('365','Giảm, Giăm, Giằm, Giặm, Giầm, Giâm, Giậm, Giấm',1),
    ('366','Giấm, Giầm, Gian, Gián',1),
    ('367','Giàn, Giãn, Giàn, Giần, Giận',1),
    ('368','Giận, Giần, Giang',1),
    ('369','Giang, Giạng, Giáng, Giàng, Giảng, Giăng',1),
    ('370','Giăng, Giặng, Giằng, Giầng, Giẩng, Gianh, Giành',1),
    ('371','Giảnh, Giầnh, Giao, Giáo',1),
    ('372','Giáo, Giảo',1),
    ('373','Giảo, Giáp, Giặp, Giấp',1),
    ('374','Giập, Giát, Giạt, Giặt, Giật, Giàu',1),
    ('375','Giâu, Giấu, Gie, Gié,Giẻ, Giếc, Giệch, Gièm, Giếm, Giền',1),
    ('376','Giêng, Giếng, Giềng, Giểnh, Gieo, Giẹo, Giéo, Giẹp, Giết, Giệu',1),
    ('377','Giệu, Giễu, Gìn, Gio, Gió',1),
    ('378','Gió, Giò, Giỏ, Giõ, Giô, Giồ',1),
    ('379','Giỏ, Giõ, Giơ, Giờ, Gióc, Gioi',1),
    ('380','Gioi, Giọi, Giòi, Giỏi, Giội, Giổi, Giới, Giợm',1),
    ('381','Giớm, Giòn, Giớn, Giỡn, Giong, Giọng, Gióng',1),
    ('382','Gióng, Giông, Giống, Giồng, Giộp, Giọt',1),
    ('383','Giọt, Giót, Giột, Giốt Giợt, Gít, Gịt, Giu, Giú, Giũ',1),
    ('384','Giũ, Giư, Giữ, Giũa, Giứa',1),
    ('385','Giứa, Giừa, Giữa, Giục, Giụi, Giùi, Giụm, Giùm',1),
    ('386','Giùm, Giun, Giún, Giùn, Giuống, Giương, Giượng, Giường, Giúp, Giựt',1),
    ('387','Giựt, Go, Gò, Gõ, Gọ, Gỗ, Gở, Gỡ',1),
    ('388','Gỡ, Góa, Góc, Gốc, Gộc, Gọi, Gòi, Gói',1),
    ('389','Gói, Gỏi, Gội, Gối, Gởi, Gom',1),
    ('390','Gốm, Gồm, Gớm, Gọn, Gòn, Gọng, Gông',1),
    ('391','Gồng, Góp, Gốp, Gộp, Gót, Gọt, Gợt, Gù, Gu, Gũ',1),
    ('392','Gừa, Gục, Gùi, Gũi, Gửi, Gún, Gừng, Guốc, Guộc, Gươm, Gườm, Gương',1),
    ('393','Gương, Gượng, Guột, Gút, Gụt',1),
    ('394','Ha, Hạ',1),
    ('395','Hạ, Há, Hà',1),
    ('396','Hà, Hả, Hác',1),
    ('397','Hạc, Hặc, Hấc, Hàc, Hạch, Hách, Hai, Hại',1),
    ('398','Hại, Hái, Hài, Hải',1),
    ('399','Hải, Hãi, Hay',1),
    ('400','Hay, Háy, Hãy, Hây, Hầy, Hẫy, Hẩy, Ham, Hạm, Hám, Hàm',1),
    ('401','Hàm, Hảm, Ham, Hàm, Hảm, Hâm',1),
    ('402','Hâm, Hầm, Hẫm, Han, Hạn, Hán, Hàn',1),
    ('403','Hàn, Hản, Hán, Hàn',1),
    ('404','Hân, Hấn, Hận, Hẫn, Hang, Hạng, Háng, Hàng',1),
    ('405','Hàng, Hảng, Hăng, Háng',1),
    ('406','Hàng, Hấng, Hắng, Hẩng, Hanh, Hạnh',1),
    ('407','Hạnh, Hành',1),
    ('408','Hành, Hảnh, Hao, Hào,',1),
    ('409','Hào, Hạo, Hảo, Háp, Hạp',1),
    ('410','Hạp, Hấp, Hát, Hạt, Hất, Háu, Hàu',1),
    ('411','Hàu, Hậu',1),
    ('412','Hậu, Hấu, Hầu,',1),
    ('413','Hầu, He, Hẹ, Hé, Hè, Hẽ, Hẻ, Hê, Hệ, Hề',1),
    ('414','Hề, Hể, Hễ, Hem, Hèm, Hẹm, Hẻm, Hềm, Hen, Hẹn',1),
    ('415','Hèn, Hến, Hê, Heo,',1),
    ('416','Heo, Héo, Hèo, Hẻo, Hẹp, Hét, Hết',1),
    ('417','Hết, Hệt, Hêu, Hểu, Hi',1),
    ('418','HI, Hì, Hí, Hỉ, Hia, Hịch, Hích, Hiếm, Hiềm, Hiệm, Hiểm',1),
    ('419','Hiểm, Hiên, Hiện Hiến, Hiền, Hiển',1),
    ('420','Hiểng, Hiếp, Hiệp',1),
    ('421','Hiệp, Hiệu, Hiếu, Hiểu',1),
    ('422','Hiểu, Him, Hin, Hỉn, Hình',1),
    ('423','Hình, Hỉnh, Híp, Hít, Hiu, Ho',1),
    ('424','Ho, Họ, Hó, Hò, Hô',1),
    ('425','Hô, Hộ, Hố, Hồ,',1),
    ('426','Hồ, Hổ',1),
    ('427','Hổ, Hơ, Hở, Hờ, Hoa',1),
    ('428','Hoa, Họa, Hóa',1),
    ('429','Hóa, Hòa, Hỏa',1),
    ('430','Hỏa, Hoác, Hoặc',1),
    ('431','Hoặc, Hoác, Hoặch, Hoách, Hoáy, Hoai, Hoại, Hoãi, Hoải, Hoài',1),
    ('432','Hoài, Hoan, Hoạn, Hoán, Hoàn',1),
    ('433','Hoàn, Hoản, Hoang, Hoáng, Hoảng',1),
    ('434','Hoầng, Hoàng, Hoanh, Hoánh, Hoành',1),
    ('435','Hoành, Hoảnh, Hoạnh, Hoạt, Hóc, Học',1),
    ('436','Học, Hốc, Hộc, Hoe',1),
    ('437','Hoe, Họe, Hòe, Hóe, Hoẻn, Hoét, Hoi, Hói, Hòi, Hỏi',1),
    ('438','Hỏi, Hôi, Hội',1),
    ('439','Hội, Hối, Hồi',1),
    ('440','Hồi, Hổi, Hơi',1),
    ('441','Hơi, Hới, Hời, Hợi, Hởi, Hỡi, Hom, Hòm',1),
    ('442','Hòm, Hóm, Hỏm, Hôm, Hổm, Hờm, Hợm, Hon, Hón, Hòn',1),
    ('443','Hòn, Hôn, Hồn',1),
    ('444','Hồn, Hỗn, H7n, Hi71n, Hờn, Hong',1),
    ('445','Họng, Hóng, Hòng, Hỏng, Hông',1),
    ('446','Hống, Hồng, Hổng, Hóp, Họp, Hộp',1),
    ('447','Hộp, Hốp, Hớp, Hợp, Hót, Hốt, Hột',1),
    ('448','Hột, Hớt, Hu, Hù, Hú, Hũ, Hủ',1),
    ('449','Hủ, Hư, Hứ, Hử',1),
    ('450','Hự, Hùa, Húa, Hưa, Hứa, Huây, Huầy, Huân, Huấn, Huẩn, Huất, Húc, Hục',1),
    ('451','Hực, Huê, Huệ, Huề, Huế, Huểnh, Hui, Hùi, Húi, Hụi, Huy, Húy',1),
    ('452','Hủy, Huịch, Huiên, Huyện, Huyền',1),
    ('453','Huyền, Huyễn, Huyết, Huyệt',1),
    ('454','Huinh, Huình, Huĩnh, Hum, Hùm, Húm, Hun, Hùn, Hung',1),
    ('455','Hung, Húng, Hùng, Hủng, Hưng',1),
    ('456','Hưng, Hứng, Hừng, Hược, Hươi, Huờn, Huông, Huồng, Huống, Hương',1),
    ('457','Hương',1),
    ('458','Hương, Hướng, Hưởng, Hường, Hươu, Húp, Hụp, Hút',1),
    ('459','Hút, Hụt, Hưu, Hữu',1),
    ('460','Hữu, Hựu',1),
    ('461','Y',1),
    ('462','Y, Ý',1),
    ('463','Ỳ, Ỷ, Yả, Yếc, Yếm, Yểm',1),
    ('464','Yên, Yến, Yêng, Yếng, Yết, Yêu',1),
    ('465','Yêu, Yếu, Yều, Yểu, Ym',1),
    ('466','Ym, Ị, Ích, Ịch, Ím, In, Ịn',1),
    ('467','Inh, Ỉnh, Ít, Ịt, Ỉu',1),
    ('468','Ké, Ke, Kẹ, Ke, Kè, Kẻ, Kẽ',1),
    ('469','Kẽ, Kê, Kệ, Kế',1),
    ('470','Kế, Kề, Kể, Kéc',1),
    ('471','Kéc, Kệch, Kem, Kèm, Kém, Kẽm, Kềm, Ken',1),
    ('472','Ken, Kén, Kèn, Kẹn, Kê, Kênh, Keo, Kẹo',1),
    ('473','Kẹo, Kéo, Kèo, Kẻo',1),
    ('474','Kẻo, Kép, Kẹp, Kết, Kêu',1),
    ('475','Kha, Khả, Kah1, Khác',1),
    ('476','Khạc, Khắc, Khấc, Khách',1),
    ('477','Khách, Khai, Khái',1),
    ('478','Khái, Khại, Khải, Khay, Khảy, Kham, Khám, Khảm, Khẩm',1),
    ('479','Khẩm, Khâm, Khan, Khán, Khản, Khăn',1),
    ('480','Khăn, Khán, Khẩn, Khấn, Khẩn, Khang, Khăng, Khảng, Khẩng, Khanh',1),
    ('481','Khanh, Khấnh, Khánh, Khảnh, Khao, Kháo, Khào, Khảo, Khạo',1),
    ('482','Kháp, Khạp, Khắp, Khấp, Khát, Khất, Khật, Khâu, Khấu, Khấu',1),
    ('483','Khậu, Khảu, Khe, Khè, Khé, Khẹ',1),
    ('484','Khẽ, Khê, Khế, Khể, Khem, Khém, Khen',1),
    ('485','Khen, Khén, Khên, Khệng, Kheo, Khéo, Khèo, Khép, Khét',1),
    ('486','Khét, Khẹt, Khêu, Khều, Khểu, Khi, Khí',1),
    ('487','Khí',1),
    ('488','Khí, Khỉ, Khì, Khịa',1),
    ('489','Khía, Khỉa, Khích, Khiêm, Khiếm, Khiểm, Khiên',1),
    ('490','Khiên, Khiển, Khiêng, Khiếp, Khiết, Khiệt, Khiêu, Khín, Khinh, Khịt, Khít',1),
    ('491','Khít, Khíu, Khìu, Khịu, Khỉu, Kho, Khò, Khó',1),
    ('492','Khó, Khô, Khố, Khổ',1),
    ('493','Khổ, Khờ, Khoa, Khóa',1),
    ('494','Khóa, Khỏa, Khoai, Khoái, Khoan',1),
    ('495','Khoan, Khoán, Khoản, Khoăn, Khoang, Khoáng',1),
    ('496','Khoáng, Khoảng, Khoanh, Khoảnh, Khoát, Khóc',1),
    ('497','Khóc, Khoe, Khóe, Khỏe, Khoen, Khoét, Khói',1),
    ('498','Khói, Khỏi, Khôi, Khối',1),
    ('499','Khơi, Khới, Khởi, Khom, Khòm, Khóm, Kớm, Khòn, Khọn, Khôn',1),
    ('500','Khôn, Khốn, Khổn, Khớn, Khờn, Khong, Khỏng, Không',1),
    ('501','Không',1),
    ('502','Không, Khống, Khổng, Khớp, Khu, Khù',1);
INSERT INTO db_dainam VALUES
    ('503','Khủ, Khú, Khư, Khự, Khử, Khứ, Khua, Khứa, Khuây, Khuấy',1),
    ('504','Khuây, Khuân, Khuẩn, Khuâng, Khuất, Khúc',1),
    ('505','Khúc, Khuy, Khuia, Khuiếc, Khuyên',1),
    ('506','Khuyên, Khuyến, Khuyển, Khuyết, Khuinh, Khuính, Khuỉnh, Khum, Khúm',1),
    ('507','Khung, Khùng, Khủng, Khứng, Khừng, Khửng, Khựng, Khước, Khươi, Khướu, Khuôn',1),
    ('508','Khuông, Khuống, Khương, Ki, Kị, Kí',1),
    ('509','Kí, Ký, Kì',1),
    ('510','Kì, Kỳ, Ký',1),
    ('511','Kỳ, Kỉ',1),
    ('512','Kia, Kìa, Kía, Kích, Kịch, Kiêm, Kiệm, Kiếm',1),
    ('513','Kiếm, Kiểm, Kiên, Kiện',1),
    ('514','Kiến',1),
    ('515','Kiến, Kiền, Kiêng, Kiềng, Kiểng',1),
    ('516','Kiểng, Kiếp',1),
    ('517','Kiếp, Kiết, Kiệt, Kiêu, Kiệu',1),
    ('518','Kiệu, Kiếu, Kiều, Kiểu, Kim',1),
    ('519','Kim, Kìm, Kịn, Kín',1),
    ('520','Kín, Kinh',1),
    ('521','Kinh, Kính',1),
    ('522','Kính, Kình, Kíp, Kịp, Kịt',1),
    ('523','Kịt, Kít, La',1),
    ('524','La, Lạ, Lá',1),
    ('525','Lá, Là, Lả, Lã',1),
    ('526','Lã, Lác, Lạc',1),
    ('527','Lạc, Lắc, Lặc, Lấc, Lách, Lạch',1),
    ('528','Lạch, Lai, Lại',1),
    ('529','Lại, Lái',1),
    ('530','Lái, Lài, Lãi, Lay, Láy, Lạy, Lảy',1),
    ('531','Lảy, Lây, Lấy',1),
    ('532','Lấy, Lầy, Lẩy, Lẫy, Lam, Lạm, Làm',1),
    ('533','Làm',1),
    ('534','Làm',1),
    ('535','Làm, Lãm',1),
    ('536','Lăm, Lắm, Lằm, Lẵm, Làm, Lâm',1),
    ('537','Lậm, Lấm, Lầm, Lẩm, Lẫm, Lan, Làn',1),
    ('538','Lạn, Lăn, Lặn, Làn, Lãn, Lân',1),
    ('539','Lân, Lận, Lấn, Lần, Lẩn',1),
    ('540','Lẩn, Lãn, Lang, Lạng',1),
    ('541','Láng, Làng, Lảng',1),
    ('542','Lảng, Lăng, Lặng',1),
    ('543','Lặng, Lắng, Làng, Lẳng, Lâng, Lấng, Lầng, Lẩng, Lanh',1),
    ('544','Lanh, Lạnh, Lánh, Lành',1),
    ('545','Lành, Lảnh, Lãnh, Lậnh, Lao',1),
    ('546','Lao, Láo, Lào',1),
    ('547','Lào, Lảo, Lão',1),
    ('548','Lão, Lạo, Lạp, Láp, Lắp, Lặp, Lấp',1),
    ('549','Lấp',1),
    ('550','Lấp, Lát, Lạt',1),
    ('551','Lất, Lật, Lau, Lạu, Láu, Làu, Lảu',1),
    ('552','Lâu, Lậu, Lấu, Lầu, Le',1),
    ('553','Le, Lẹ, Lé, Lè, Lẻ, Lẽ',1),
    ('554','Lẽ, Lê, Lệ',1),
    ('555','Lệ, Lế, Lề, Lể, Lễ',1),
    ('556','Lễ, Léc, Lẹc',1),
    ('557','Lếch, Lệch, Lem, Lẹm, Lém, Lèm, Lẻm, Len, Lén, Lèn',1),
    ('558','Lẹn, Lẻn, Lên, Lện, Lền, Lênh, Lệnh',1),
    ('559','Lệnh, Lểnh, Leo, Lẹo, Léo, Lèo',1),
    ('560','Lèo, Lẻo, Lép, Lẹp, Lét, Lẹt, Lết, Lệt',1),
    ('561','Lệt, Lêu, Lều, Lếu, Lểu, Li',1),
    ('562','Li, Ly, Lý',1),
    ('563','Lý, Lỳ, Lia, Lịa, Lìa, Lía',1),
    ('564','Lía, Lỉa, Lịch, Liếc, Liệc, Liêm, Liệm, Liếm',1),
    ('565','Liếm, Liềm, Liểm, Liên, Liện, Liến, Liền',1),
    ('566','Liền, Liễn, Liêng, Liệng, Liếng, Liểng, Liếp',1),
    ('567','Liếp, Liệp, Liệt, Liêu, Liệu',1),
    ('568','Liệu, Liễu, Liều, Lim, Lím, Linh',1),
    ('569','Linh, Lịnh, Lính, Lĩnh, Lịp',1),
    ('570','Lít, Lịt, Liu, Lịu, Líu, Lo',1),
    ('571','Lọ, Ló, Lỏ, Lò, Lô, Lộ',1),
    ('572','Lộ, Lố, Lồ, Lổ, Lỡ',1),
    ('573','Lỡ, Lỗ, Lơ, Lợ, Lớ, Lờ',1),
    ('574','Lờ, Lở, Lỡ, Loa, Lòa',1),
    ('575','Lòa, Lõa, Lỏa, Loại, Loài, Loan, Loạn, Loán',1),
    ('576','Loán, Loàn, Loát, Lóc, Lọc, Lộc',1),
    ('577','Lộc, Lốc, Loi, Lọi, Lòi, Lói',1),
    ('578','Lói, Lõi, Lôi, Lội, Lới, Lồi',1),
    ('579','Lồi, Lỗi, Lơi, Lợi',1),
    ('580','Lợi, Lới, Lời',1),
    ('581','Lời, Lom, Lòm, Lóm, Lõm, Lôm, Lốm, Lồm, Lỗm, Lơm, Lờm, Lởm, Lon',1),
    ('582','Lọn, Lòn, Lón, Lỏn, Lộn',1),
    ('583','Lộn, Lốn, Lồn, Lổn, Lơn, Lợn, Lớn',1),
    ('584','Lớn, Lờn, Long',1),
    ('585','Long, Lọng, Lóng, Lòng',1),
    ('586','Lòng',1),
    ('587','Lòng, Lỏng, Lông',1),
    ('588','Lông, Lộng, Lồng, Lổng',1),
    ('589','Lổng, Lóp, Lọp, Lốp, Lộp, Lợp, Lớp, Lót',1),
    ('590','Lót, Lọt, Lốt, Lột, Lợt, Lớt, Lu',1),
    ('591','Lu, Lú, Lù, Lũ, Lư',1),
    ('592','Lư, Lừ, Lữ, Lự, Lua, Lụa, Lúa',1),
    ('593','Lúa, Lùa, Lưa, Lựa, Lừa',1),
    ('594','Lừa, Lứa, Lửa',1),
    ('595','Lửa, Luân',1),
    ('596','Luận, Luật, Lúc, Lục',1),
    ('597','Lục, Lực',1),
    ('598','Lực, Lui, Lụi, Lúi, Lùi, Lủi',1),
    ('599','Lủi, Lụy, Luyện, Luyến, Lum, Lùm, Lúm, Lụm, Lủm',1),
    ('600','Lủm, Lụn, Lún, Lùn, Lũn, Lung, Lúng, Lùng',1),
    ('601','Lùng, Lủng, Lũng, Lưng, Lựng, Lứng, Lừng',1),
    ('602','Lửng, Lững, Luốc, Luộc, Lược, Luõi, Lưới',1),
    ('603','Lưới, Lưỡi, Luôm, Lượm',1),
    ('604','Lườm, Luôn, Luồn, Lươn, Lượn, Lườn, Luông, Luống',1),
    ('605','Luồng, Lương',1),
    ('606','Lương, Lượng, Lường, Lưỡng, Luốt',1),
    ('607','Luột, Lướt, Lượt, Lúp, Lụp, Lút, Lụt, Lứt, Lưu',1),
    ('608','Lưu, Lựu, Luựt',1),
    ('1','Ma',2),
    ('2','Ma, Mạ, Má, Mà',2),
    ('3','Mả, Mã',2),
    ('4','Mác, Mạc, Mắc',2),
    ('5','Mắc, Mặc, Mấc, Mách, Mạch',2),
    ('6','Mạch, Mai',2),
    ('7','Mai, Mại, Mái, Mài, Mãi',2),
    ('8','Mãi, Mại, May, Mạy, Máy',2),
    ('9','Máy, Mày, Mảy, Mây',2),
    ('10','Mây, Mấy, Mầy',2),
    ('11','Mầy , Mẩy, Mám, Mam, Mảm, Mâm, Mậm',2),
    ('12','Mậm, Mẩm, Mấm, Mầm, Man, Mạn, Mán, Màn, Mãn',2),
    ('13','Mãn, Man, Mặn, Mằn, Mản, Mán',2),
    ('14','Mân, Mận, Mấn, Mần, Mãn, Mẫn, Mang',2),
    ('15','Mang, Mạng',2),
    ('16','Mạng, Máng, Màng, Mảng, Măng',2),
    ('17','Măng, Màng, Mắng, Mâng, Mầng, Mãng, Manh',2),
    ('18','Manh, Mạnh, Mánh, Mành, Mảnh',2),
    ('19','Mảnh, Mao, Mạo, Mão',2),
    ('20','Mão, Mào, Mạp, Mặp, Mập, Mấp, Mát, Mạt',2),
    ('21','Mạt, Mắt',2),
    ('22','Mắt, Mặt',2),
    ('23','Mặt',2),
    ('24','Mất, Mật, Mau, Máu',2),
    ('25','Máu, Màu',2),
    ('26','Mâu, Mậu, Mấu, Mầu, Mẫu, Me',2),
    ('27','Me, Mẹ, Mé, Mè, Mẻ',2),
    ('28','Mẻ, Mẽ, Mê, Mế, Mề, Mễ, Méc, Mếch, Mem',2),
    ('29','Mem, Mèm, Mém, Mềm, Men, Mén, Mèn, Mẻn, Mên, Mến, Mền, Mển, Mênh, Meo',2),
    ('30','Meo, Mẹo, Méo, Mèo, Mẻo, Mép',2),
    ('31','Mép, Mẹp, Mét, Mệt, Mếu, Mểu, Mi, Mị',2),
    ('32','Mí, Mì, Mĩ, Mía, Mỉa',2),
    ('33','Mích, Miên, Miền, Miến, Miễn, Miêng, Miệng',2),
    ('34','Miệng, Miếng',2),
    ('35','Miếng, Miểng, Miết, Miệt, Miêu, Miều, Miễu',2),
    ('36','Miếu, Mím, Mỉm, Min, Mịn, Mỉn, Minh',2),
    ('37','Minh, Mỉnh, Mình, Mít, Mịt',2),
    ('38','Mo, Mó, Mò, Mỏ',2),
    ('39','Mỏ, Mõ, Mọ, Mô, Mộ',2),
    ('40','Mộ, Mố, Mồ, Mỏ, Mỗ, Mơ',2),
    ('41','Mơ, Mợ, Mớ, Mờ, Mở',2),
    ('42','Mở, Mỡ, Móc, Mọc, Mốc',2),
    ('43','Mốc, Mộc, Moi, Mọi',2),
    ('44','Mọi, Mòi, Mỏi, Môi',2),
    ('45','Môi, Mội, Mối, Mồi',2),
    ('46','Mồi, Mỗi, Mới, Mời, Mợi, Móm, Mòm',2),
    ('47','Mỏm, Mồm, Mớm, Mờm, Mon, Mọn, Món, Mòn, Mỏn, Môn',2),
    ('48','Môn, Mơn, Mởn, Mớn, Mong, Mọng, Móng',2),
    ('49','Móng, Mòng, Mỏng, Mông, Mộng,',2),
    ('50','Mống, Mồng, Mỏng, Mơng, Mợp Móp, Mốp, Mớp Mót',2),
    ('51','Mót, Mọt, Mốt, Một',2),
    ('52','Một, Mớt, Mởu, Mu, Mụ, Mú, Mù, Mủ, Mũ',2),
    ('53','Mũ, Mua, Múa, Mùa',2),
    ('54','Mùa, Mưa, Mựa, Mứa, Mửa, Múc',2),
    ('55','Mú, Mục, Mực',2),
    ('56','Mực, Mức, Mủi, Múi, Mùi, Mũi',2),
    ('57','Mũi, Mun, Mụn, Mún, Mùn, Mung, Mùng, Mủng, Mưng, Mừng, Mửng',2),
    ('58','Mửng, Muội, Muối, Muồi, Muỗi, Mươi, Mưới, Mười',2),
    ('59','Muôn, Muộn, Muốn, Mướn, Mượn, Muông, Muống, Muồng',2),
    ('60','Muồng, Muổng, Mược, Mương, Mượng, Mường, Mưởng, Mướp, Mướt, Mưỡu, Múp, Mút, Mụt',2),
    ('61','Mụt, Mứt, Mưu',2),
    ('62','Na, Ná, Nà, Nả, Nạ, Nạc, Nắc, Nặc, Nấc',2),
    ('63','Nấc, Nách, Nai, Nại, Nái, Nài',2),
    ('64','Nải, Nay, Nạy, Náy, Này, Nảy, Nãy, Nây, Nấy, Nầy',2),
    ('65','Nầy, Nậy, Nẩy, Nam',2),
    ('66','Nam, Nạm, Nám, Nàm, Năm, Nắm, Nằm',2),
    ('67','Nằm, Nấm,',2),
    ('68','Nấm, Nạn, Nán, Nàn, Năn, Nặn, Nắn, Nân, Nận',2),
    ('69','Nận, Nấn, Nần, Nang, Nạng, Náng, Nàng, Năng, Nặng',2),
    ('70','Nặng, Náng, Nàng, Nâng, Nậng, Nấng, Nanh',2),
    ('71','Nanh, Nạnh, Nành, Nao, Náo, Nạo, Nào, Não',2),
    ('72','Não, Náp, Nạp, Nắp, Nập, Nát',2),
    ('73','Nát, Nạt, Nau, Náu, Nâu, Nậu, Nấu, Nẫu, Ne, Né, Nẻ',2),
    ('74','Nẻ, Nè, Nê, Nệ, Nề, Nể, Nễ, Nem, Ném, Nêm',2),
    ('75','Nêm, Nệm, Nếm, Nén, Nên, Nện',2),
    ('76','Nền, Nếnh, Neo, Nẹo, Néo, Nèo, Nẻo, Nép, Nẹp',2),
    ('77','Nếp, Nét, Nẹt, Nết, Nêu',2),
    ('78','Nêu, Nếu, Nga, Ngà, Ngả, Ngã',2),
    ('79','Ngã, Ngạc, Ngắc, Ngạch, Ngách, Ngai, Ngại',2),
    ('80','Ngại, Ngái, Ngài, Ngải, Ngãi, Ngay',2),
    ('81','Ngay, Ngáy, Ngày',2),
    ('82','Ngày, Ngãy, Ngây, Ngầy, Ngấy, Ngàm, Ngăm, Ngặm, Ngám, Ngàm',2),
    ('83','Ngàm, Ngậm, Ngấm, Ngầm, Ngăm, Ngán, Ngàn',2),
    ('84','Ngàn, Ngạn, Ngăn, Ngắn, Ngân, Ngấn, Ngần',2),
    ('85','Ngẩn, Ngang, Ngáng, Ngàng, Ngảng, Ngạnh',2),
    ('86','Ngạnh, Ngánh, Ngành, Ngảnh, Ngao, Ngạo, Ngáo, Ngáp',2),
    ('87','Ngáp, Ngạp, Ngát, Ngạt, Ngặt, Ngất, Ngật, Ngâu, Nghe',2),
    ('88','Nghe, Nghẹ, Nghé, Nghè, Nghê, Nghệ',2),
    ('89','Nghệ, Nghề, Nghể, Nghếch, Nghệch, Nghẹn',2),
    ('90','Nghẹn, Nghén, Nghếng, Nghênh, Nghểnh, Ngheo, Nghéo, Nghèo, Nghẻo, Nghẹt',2),
    ('91','Nghét, Nghêu, Nghẽu, Nghệu, Nghếu, Nghi',2),
    ('92','Nghi, Nghí, Nghì, Nghỉ, Nghĩ, Nghĩa',2),
    ('93','Nghịch, Nghiêm, Nghiệm, Nghiềm, Nghiên',2),
    ('94','Nghiến, Nghiền, Nghiêng, Nghiểng, Nghiếp, Nghiệp, Nghiệt, Nghiêu',2),
    ('95','Nghiêu, Nghìn, Nghinh, Nghỉnh, Nghít, Ngo, Ngọ, Ngó, Ngò, Ngỏ',2),
    ('96','Ngỏ, Ngõ, Ngô, Ngộ, Ngỗ, Ngơ',2),
    ('97','Ngơ, Ngờ, Ngỡ, Ngợ, Ngoa, Ngỏo, Ngõa, Ngoai, Ngoại',2),
    ('98','Ngoại, Ngoái, Ngoài, Ngoải, Ngoay, Ngoáy, Ngoảy, Ngoàm, Ngoảm',2),
    ('99','Ngoan, Ngoạn, Ngoao, Ngoại, Ngoát, Ngóc, Ngọc',2),
    ('100','Ngọc, Ngốc, Ngoe, Ngoẻn, Ngoeo, Ngoẻo, Ngoẹo, Ngoéo, Ngoi, Ngói',2),
    ('101','Ngói, Ngòi, Ngỏi, Ngôi, Ngồi',2),
    ('102','Ngồi, Ngội, Ngơi, Ngợi, Ngời, Ngỡi, Ngỏm, Ngon',2),
    ('103','Ngon, Ngọn, Ngón, Ngỏn, Ngôn',2),
    ('104','Ngốn, Ngổn, Ngơn, Ngớn, Ngỡn, Ngong, Ngọng, Ngóng, Ngõng, Ngồng, Ngỗng, Ngợp, Ngót',2),
    ('105','Ngọt, Nột, Ngốt, Ngớt, Ngớu, Ngu',2),
    ('106','Ngu, Ngụ, Ngủ, Ngũ',2),
    ('107','Ngũ, Ngư, Ngự, Ngừ, Ngữ',2),
    ('108','Ngữ, Ngựa',2),
    ('109','Ngựa, Ngứa, Ngừa, Ngửa, Ngúc, Ngục',2),
    ('110','Ngục, Ngực, Ngui, Ngùi, Nguịch, Nguích, Nguít, Nguy, Ngụy, Ngùy, Ngửi, Nguyên',2),
    ('111','Nguyên, Nguyện, Nguyền, Nguyễn, Nguyệt',2),
    ('112','Nguyệt, Nguyu, Ngủm, Ngún, Ngùn, Ngụn, Ngung, Ngùng, Ngủng, Ngưng, Ngừng, Ngững, Ngước, Ngược',2),
    ('113','Ngược, Nguôi, Nguội, Ngươi, Người',2),
    ('114','Người, Nguồn, Ngươn, Ngưởng, Ngút, Ngưu',2),
    ('115','Ngưu, Nha, Nhá, Nhả, Nhã, Nhà',2),
    ('116','Nhà',2),
    ('117','Nhà, Nhác, Nhạc, Nhắc, Nhách, Nhai, Nhái',2),
    ('118','Nhái, Nhại, Nhay, Nhạy, Nháy, Nhảy',2),
    ('119','Nhảy, Nhây, Nhấy, Nhầy, Nhẩy, Nham, Nhám, Nhàm, Nhăm, Nhặm, Nhắm',2),
    ('120','Nhắm, Nhằm, Nhẵm, Nhâm, Nhậm, Nhấm',2),
    ('121','Nhẩm, Nhan, Nhạn, Nhàn, Nhãn',2),
    ('122','Nhãn, Nhăn, Nhắn, Nhàn, Nhận,',2),
    ('123','Nhận, Nhấn, Nhẫn, Nhang, Nháng, Nhảng, Nhăng, Nhằng, Nhãng, Nhánh',2),
    ('124','Nhánh, Nhành, Nhảnh, Nhao, Nhạo, Nhào, Nhão, Nháo, Nháp, Nhạp, Nhắp, Nhấp, Nhập',2),
    ('125','Nhập, Nhát, Nhắt, Nhặt, Nhất',2),
    ('126','Nhất, Nhật, Nhau, Nháu, Nhàu',2),
    ('127','Nhậu, Nhầu, Nhẹ, Nhè, Nhẻ, Nhẽ, Nhê, Nhệ',2),
    ('128','Nhệ, Nhem, Nhẹm, Nhèm, Nhém, Nhen, Nhèn, Nhện, Nheo, Nhèo, Nhẹo, Nhẻo, Nhẹp',2),
    ('129','Nhép, Nhét, Nhẹt, Nhểu, Nhếu, Nhi, Nhị, Nhì, Nhí, Nhỉ, Nhĩ, Nhích',2),
    ('130','Nhích, Nhiếc, Nhiệm, Nhiễm, Nhiên, Nhiền, Nhiệt, Nhiêu, Nhiều',2),
    ('131','Nhiều, Nhiễu, Nhĩm, Nhím, Nhịn, Nhín, Nhìn',2),
    ('132','Nhìn, Nhíp, Nhịp, Nhít, Nhíu, Nho',2),
    ('133','Nho, Nhỏ, Nhổ',2),
    ('134','Nhỗ, Nhơ, Nhợ, Nhớ, Nhờ, Nhở, Nhoái, Nhóc',2),
    ('135','Nhóc, Nhọc, Nhoi, Nhói, Nhồi, Nhối, Nhơi, Nhởi, Nhom, Nhóm, Nhởm',2),
    ('136','Nhớm, Nhờm, Nhọn, Nhón, Nhòn, Nhôn, Nhộn, Nhơn',2),
    ('137','Nhơn',2),
    ('138','Nơn, Nhợn, Nhờn, Nhớn, Nhỡn, Nhòng, Nhóng, Nhỏng, Nhông, Nhộng, Nhồng, Nhóp',2),
    ('139','Nhớp, Nhót, Nhọt, Nhốt, Nhột, Nhớt, Nhợt, Nhu',2),
    ('140','Nhũ, Nhủ, Nhụ, Nhú, Như, Nhứ, Nhừ, Nhữ, Nhử, Nhụa, Nhúa, Nhựa',2),
    ('141','Nhuân, Nhuận, Nhuần, Nhúc, Nhục, Nhuệ, Nhức, Nhui',2),
    ('142','Nhùi, Nhủi, Nhụy, Nhuyễn, Nhum, Nhúm, Nhũm, Nhún, Nhung',2),
    ('143','Nhung, Nhúng, Nhùng, Nhũng, Nhưng, Nhửng, Những, Nhuốc',2),
    ('144','Nhuốc, Nhược, Nhưới, Nhượi, Nhuộm, Nhuốm, Nhương, Nhượng',2);
INSERT INTO db_dainam VALUES
    ('145','Nhường, Nhướng, Nhưởng, Nhuốt, Nhút, Nhứt, Nhựt',2),
    ('146','Nhựt, Ni, Nì, Ní, Nỉ, Nĩ, Nia, Nỉa, Ních, Nịch, Niêm, Niệm',2),
    ('147','Niệm, Niềm, Niên, Niền, Niểng',2),
    ('148','Niếp, Niệt, Niết, Niêu, Niểu, Niếu, Nín, Ninh, Nịnh',2),
    ('149','Nính, Níp, Nít, Nịt, Niu, Nịu, Níu, No',2),
    ('150','No, Nọ, Nó, No, Nỏ, Nõ, Nô, Nộ',2),
    ('151','Nộ, Nố, Nồ, Nổ, Nỗ, Nơ, Nớ, Nợ',2),
    ('152','Nợ, Nở, Nỡ',2),
    ('153','Nỡ, Noa, Nọc, Nóc, Noi, Nọi',2),
    ('154','Nói',2),
    ('155','Nói, Nòi, Nôi, Nội',2),
    ('156','Nội, Nối, Nồi',2),
    ('157','Nồi, Nổi, Nỗi, Nơi',2),
    ('158','Nơi, Nới, Nom, Nôm, Nộm, Nồm, Nơm, Non',2),
    ('159','Non, Nón, Nỏn, Nôn',2),
    ('160','Nôn, Nợn, Nong, Nọng, Nóng, Nòng, Nông',2),
    ('161','Nông, Nống, Nồng, Nỏng, Nóp, Nốp, Nộp, Nớp, Nột, Nốt, Nớt, Nớu, Nu, Nụ',2),
    ('162','Nụ, Nú, Nư, Nữ, Nua, Nủa, Nưa, Nứa, Nửa',2),
    ('163','Nửa, Nữa, Núc, Nục, Nức, Nực, Núi',2),
    ('164','Núi, Nụi, Nùi, Núm, Nung, Núng, Nùng, Nũng, Nưng',2),
    ('165','Nứng, Nừng, Nựng, Nuộc, Nước,',2),
    ('166','Nước, Nược, Nuôi, Nuối, Nuốm',2),
    ('167','Nuốm, Nươm, Nườm, Nuông, Nương, Nướng, Nượp, Nuốt, Núp',2),
    ('168','Nút, Nứt, Nựu, O, Ó',2),
    ('169','Ó, Ọ, Ò, Ô,',2),
    ('170','Ố, Ổ, Ồ, Ơ, Ợ, Ớ, Ờ, Ở',2),
    ('171','Ở, Oa, Oà',2),
    ('172','Oà, Oạc, Oai, Oải, Oam, Oan',2),
    ('173','Oan, Oán, Oản, Oáp, Oặt, Óc, Ọc',2),
    ('174','Ọc, Ốc, Oi, Ói, Òi',2),
    ('175','Ỏi, Ôi, Ối, Ổi, Ỗi, Ội, Ơi, Ới, Om, Ôm',2),
    ('176','Ôm, Ốm, Ỏn, Ôn, Õn, Ổn, Ơn',2),
    ('177','Ơn, Ớn, Ong',2),
    ('178','Óng, Ỏng, Ông, Ỗng, Ống',2),
    ('179','Ống, Ọp, Óp, Ốp, Ót, Ọt, Ốt, Ột',2),
    ('180','Ột, Ớt, Ợt, Pha, Phá',2),
    ('181','Phá, Phà, Phả, Phác, Phắc, Phách',2),
    ('182','Phách, Phạch, Phai, Phái, Phải',2),
    ('183','Phải, Phay, Pháy, Phảy, Phạm',2),
    ('184','Phàm, Phảm, Phan, Phạn, Phán',2),
    ('185','Phàn, Phản, Phăn, Phân',2),
    ('186','Phân, Phận',2),
    ('187','Phận, Phấn, Phần',2),
    ('188','Phần, Phẩn, Phang, Phãng, Phăng, Phảng, Phẩng',2),
    ('189','Phanh, Phành, Phao, Pháo, Phào, Phảo, Phạp',2),
    ('190','Pháp, Phặp, Phập, Phát',2),
    ('191','Phát',2),
    ('192','Phát, Phạt, Phát, Phất, Phật',2),
    ('193','Phật, Phau, Phậu, Phẩu, Phe, Phé, Phê, Phế',2),
    ('194','Phế, Phếch, Phệch, Phen, Phèn,Phên, Phện, Phềnh, Pheo',2),
    ('195','Phèo, Phép',2),
    ('196','Phép, Phẹt, Phét, Phết, Phệt, Phêu, Phếu, Phều, Phi',2),
    ('197','Phi, Phí, Phì, Phỉ',2),
    ('198','Phía, Phỉch, Phích, Phiên, Phiện, Phiến, Phiền',2),
    ('199','Phiền, Phiêu, Phiếu, Phím, Phình, Phỉnh, Pho, Phó',2),
    ('200','Phò, Phô, Phố, Phổ, Phơ, Phờ, Phớ, Phở',2),
    ('201','Phở, Phọc, Phóc, Phoi, Phối, Phỏi, Phơi, Phới, Phởi, Phớm, Phồn, Phong',2),
    ('202','Phong',2),
    ('203','Phong, Phóng, Phòng',2),
    ('204','Phòng, Phỏng, Phộng, Phồng, Phổng, Phốp, Phớt',2),
    ('205','Phớt, Phu, Phụ',2),
    ('206','Phụ, Phú',2),
    ('207','Phú, Phù, Phủ',2),
    ('208','Phủ, Phúc',2),
    ('209','Phúc, Phục',2),
    ('210','Phục, Phức, Phui, Phúi, Phủi, Phun, Phún, Phung, Phụng',2),
    ('211','Phụng, Phúng, Phùng, Phủng, Phửng, Phừng, Phước',2),
    ('212','Phước, Phược, Phướn, Phuông, Phương',2),
    ('213','Phương, Phượng, Phưởng, Phúp, Phụp, Phút',2),
    ('214','Phứt, Qua',2),
    ('215','Qua, Quà, Quạ, Quá',2),
    ('216','Quá, Quả',2),
    ('217','Quả, Quác, Quách, Quạch, Quấc, Quai, Quái',2),
    ('218','Quái, Quải, Quay, Quày, Quảy, Quây, Quậy',2),
    ('219','Quấy, Quầy, Quặm, Quắm, Quan',2),
    ('220','Quan',2),
    ('221','Quan, Quán, Quàn',2),
    ('222','Quàn, Quản, Quăn, Quặn, Quán, Quàn, Quân',2),
    ('223','Quân, Quận',2),
    ('224','Quận, Quần, Quấn, Quẩn, Quang',2),
    ('225','Quang, Quảng, Quãng, Quặng, Quâng, Quãng, Quầng',2),
    ('226','Quầng, Quanh, Quạnh, Quành, Quánh, Quao, Quào, Quắp, Quát',2),
    ('227','Quát, Quạt, Quất, Quật, Quạu, Quáu, Quảu',2),
    ('228','Quấu, Que, Què, Quẻ, Qué, Quẽ, Quê',2),
    ('229','Quế, Quệ, Quệch, Quen, Quén, Quèn, Quên',2),
    ('230','Quên, Quến, Queo, Quéo, Quèo, Quẹo, Quẹp, Quẹt',2),
    ('231','Quẹt, Quét, Quệt, Quết, Quều, Qui',2),
    ('232','Qui, Quị, Quí',2),
    ('233','Quí, Quì, Quỉ',2),
    ('234','Quỉ, Quịch, Quiên, Quyên, Quyện, Quyến, Quyền',2),
    ('235','Quyền, Quiến, Quyển, Quyệt, Quyết, Quính',2),
    ('236','Quít, Quơ, Quở, Quớ, Quờ, Quốc',2),
    ('237','Quốc, Qưới, Qưởn, Quớt',2),
    ('238','Ra',2),
    ('239','Ra, Rạ, Rá',2),
    ('240','Rá, Rà, Rả, Rã, Rạc, Rác',2),
    ('241','Rác, Rặc, Rậc, Rách, Rạch, Rái',2),
    ('242','Rái, Rài, Rải, Rãi, Rạy, Ráy, Rày, Rảy, Rãy, Rây',2),
    ('243','Rầy, Rẫy, Rẩy, Ram, Rám, Rạm, Ràm, Răm, Rặm, Rắm, Rẳm, Rằm, Râm',2),
    ('244','Rầm, Rậm, Rấm, Rầm, Ran, Rạn, Rán',2),
    ('245','Rán, Ràn, Răn, Rặn, Rấn,',2),
    ('246','Rấn, Rằn, Rẩn, Rân, Rận, Rần, Rấn, Rang, Rạng',2),
    ('247','Ráng, Ràng, Rảng, Răng',2),
    ('248','Răng, Rằng, Rẩng, Rậng, Ranh, Rạnh, Rành, Rảnh',2),
    ('249','Rảnh, Rãnh, Rao, Ráo, Rào',2),
    ('250','Rào, Rạo, Rảo, Rạp, Ráp, Rắp, Rấp, Rập',2),
    ('251','Rạt, Rát, Rất, Rau, Rảu, Ràu, Ráu, Râu',2),
    ('252','Râu, Rầu, Re, Ré, Rẻ',2),
    ('253','Rẽ, Rè, Rê, Rế, Rề, Rể',2),
    ('254','Rễ, Rếch, Rếm, Ren, Rén, Rèn, Rên, Rền, Rềnh, Rệnh, Rểnh',2),
    ('255','Rễnh, Reo, Réo, Rèo, Rẻo, Rệp, Rẹt, Rét, Rệt, Rêu, Rệu',2),
    ('256','Rệu, Rều, Rểu, Ri, Rị, Rí, Rỉ, Rì, Rĩ, Ria, Rịa, Rìa, Rỉa',2),
    ('257','Rích, Rịch, Riệc, Riện, Riến, Riêng, Riềng, Riết, Riêu',2),
    ('258','Rim, Rím, Rinh, Rình, Rịnh, Rỉnh, Rít, Rịt, Riu, Ríu',2),
    ('259','Rìu, Ro, Rò, Rọ, Ró, Rỏ, Rõ, Rô, Rộm Rổ, Rỗ',2),
    ('260','Rỗ, Rố, Rơ, Rợ, Rớ, Rờ, Rỡ, Rọc, Róc, Rộc',2),
    ('261','Rốc, Roi, Rọi, Rỏi, Ròi, Rói, Rội, Rối',2),
    ('262','Rối, Rồi, Rổi, Rơi, Rợi, Rời, Rởi',2),
    ('263','Rom, Rọm, Ròm, Róm, Rõm, Rôm, Rơm, Rờm, Rón, Ròn, Rộn, Rốn, Rổn, Rởn',2),
    ('264','Rởn, Rong, Róng, Ròng, Rỏng, Rộng',2),
    ('265','Rộng, Rống, Rồng, Rổng, Rốp',2),
    ('266','Rốp, Rợp, Rọt, Rót, Rột, Rốt, Rớt, Rợt, Rợu, Ru',2),
    ('267','Rú, Rủ, Rù, Rũ, Rứ, Rua, Rùa, Rủa, Rựa',2),
    ('268','Rứa, Rửa, Rữa, Rục, Rúc, Rực, Rui',2),
    ('269','Rui, Rụi, Rủi, Rum, Rùm, Rụm, Run, Rún, Rùn',2),
    ('270','Rủn, Rung, Rụng, Rúng, Rùng, Rủng, Rưng, Rựng, Rừng',2),
    ('271','Rừng, Ruốc, Rước, Ruồi, Ruổi, Rươi, Rưới, Rưỡi',2),
    ('272','Rưỡi, Rướm, Ruông, Ruộng, Ruồng, Rượn, Rướn, Rương',2),
    ('273','Rương, Rượng, Rường, Ruột, Rượt',2),
    ('274','Rượu, Rút',2),
    ('275','Rút, Rụt, Rứt, Rựt, Sa',2),
    ('276','Sa, Sạ, Sá, Sà, Sả, Sã',2),
    ('277','Sã, Sạc, Sác, Sắc',2),
    ('278','Sắc, Sặc, Sách',2),
    ('279','Sách, Sạch, Sai',2),
    ('280','Sai, Sái, Sài, Sải',2),
    ('281','Sãi, Say, Sày, Sảy, Sãy, Sây, Sậy, Sấy, Sầy',2),
    ('282','Sẩy, Sam, Sàm, Sám, Săm, Sặm, Sắm, Sẳm, Sâm',2),
    ('283','Sâm, Sấm, Sầm, Sẩm, San, Sạn, Sán, Sàn',2),
    ('284','Sàn, Sản, Săn, Sắn, Sằn, Sẳn, Sân',2),
    ('285','Sân, Sấn, Sận, Sang, Sáng',2),
    ('286','Sáng, Sàng, Sảng, Săng',2),
    ('287','Sâng, Sầng, Sanh, Sánh, Sành, Sảnh',2),
    ('288','Sảnh, Sao',2),
    ('289','Sao, Sạo, Sáo, Sào, Sảo',2),
    ('290','Sáp, Sạp, Sắp, Sấp',2),
    ('291','Sấp, Sập, Sạt, Sát, Sắt',2),
    ('292','Sắt, Sặt, Sau, Sáu, Sâu',2),
    ('293','Sâu, Sấu, Sầu, Sẩu, Se',2),
    ('294','Sè, Sẻ, Sẽ, Sệ, Sề, Sể, Sém, Sen',2),
    ('295','Sẻn, Sên, Sến, Sền, Sênh, Séo, Sẹo, Sệp, Sét, Sẹt, Sết, Sệt, Sếu, Sểu',2),
    ('296','Si, Sị, Sí, Sì, Sĩ, Sịa, Sỉa, Siếc',2),
    ('297','Siểm, Siển, Siêng, Siết, Siêu, Sim, Sinh',2),
    ('298','Sinh, Sính, Sình, Sỉnh, Sít',2),
    ('299','So, Sọ, Sò, Sỏ, Sô, Sồ, Sộ, Số',2),
    ('300','Số, Sổ',2),
    ('301','Sổ, Sơ, Sợ',2),
    ('302','Sớ, Sờ, Sở',2),
    ('303','Sở, Soan, Soạn, Soán, Soát, Sóc',2),
    ('304','Sọc, Sốc, Sộc, Soi, Sói, Sòi, Sỏi, Sõi, Sôi',2),
    ('305','Sôi, Sồi, Sợi, Sóm, Sọm, Sòm, Sớm, Son',2),
    ('306','Son, Són, Sồn, Sổn, Sơn',2),
    ('307','Sơn, Sớn, Sờn, Sởn, Song, Sống, Sòng',2),
    ('308','Sòng, Sõng, Sòng, Sống',2),
    ('309','Sống, Sộp, Sọt, Sót, Sột, Sốt, Sớt, Su',2),
    ('310','Su, Sụ, Sù, Sú, Sủ, Sư, Sự',2),
    ('311','Sự, Sừ, Sứ',2),
    ('312','Sứ, Sử',2),
    ('313','Sua, Sủa, Sưa, Sứa, Sửa, Sữa',2),
    ('314','Sữa, Suất, Sục, Súc, Sực',2),
    ('315','Sực, Sức, Sui, Sùi, Suy',2),
    ('316','Suy, Súy, Suyển, Sum, Súm, Sụm, Sụn, Sún, Sung',2),
    ('317','Sung, Súng, Sùng',2),
    ('318','Sùng, Sủng, Sưng, Sựng, Sửng, Sững',2),
    ('319','Sững, Sứng, Suôi, Suối, Sươi, Sưởi, Suôn, Suổn, Sươn, Sườn, Sương',2),
    ('320','Sương, Sượng, Sướng, Suốt, Sướt, Sụp, Súp, Sụt',2),
    ('321','Sụt, Sút, Sứt, Sựt, Sưu, Sửu',2),
    ('322','Ta, Tạ, Tá',2),
    ('323','Tá, Tà, Tả, Tã, Tác',2),
    ('324','Tác, Tạc, Tắc, Tặc',2),
    ('325','Tấc, Tách, Tai',2),
    ('326','Tai',2),
    ('327','Tai, Tại, Tái, Tài',2),
    ('328','Tài',2),
    ('329','Tải, Tay',2),
    ('330','Tay',2),
    ('331','Tay, Táy, Tày, Tây',2),
    ('332','Tây, Tấy, Tẩy, Tam',2),
    ('333','Tam, Tạm, Tám, Tàm, Tăm, Tắm',2),
    ('334','Tắm, Tằm, Tâm',2),
    ('335','Tâm, Tấm',2),
    ('336','Tấm, Tầm, Tẩm, Tan',2),
    ('337','Tan, Tạn, Tán, Tàn',2),
    ('338','Tàn, Tản, Tăn, Tặn, Tằn, Tẩn, Tân',2),
    ('339','Tân, Tận, Tấn, Tần',2),
    ('340','Tấn, Tần, Tẩn, Tang',2),
    ('341','Tang, Tạn, Táng Tàng',2),
    ('342','Tàng, Tảng, Tăng, Tặng, Tằng, Tắng, Tâng, Tầng',2),
    ('343','Tầng, Tanh, Tạnh, Tánh',2),
    ('344','Tánh, Tành, Tao, Tạo, Táo',2),
    ('345','Tao, Tảo, Tạp',2),
    ('346','Tạp, Táp, Tấp, Tập, Tạt',2),
    ('347','Tạt, Tát, Tắt, Tất',2),
    ('348','Tất, Tật, Tau, Táu, Tàu',2),
    ('349','Tàu, Tâu, Tấu, Tẩu',2),
    ('350','Te, Tẹ, Té, Tè, Tẻ, Tê',2),
    ('351','Tê, Tệ, Tế',2),
    ('352','Tế, Tề, Tể, Tếch, Tém, Tèm, Têm',2),
    ('353','Têm, Ten, Tên, Teo, Tẹo, Tép, Tét',2),
    ('354','Tét, Tẹt, Tết, Tha',2),
    ('355','Thá, Thà, Thả, Thác, Thắc, Thách',2),
    ('356','Thách, Thạch',2),
    ('357','Thạch, Thai, Thái',2),
    ('358','Thái, Thaì, Thại, Thải, Thay, Tháy, Thày, Thảy, Thây, Thấy',2),
    ('359','Thấy, Thầy',2),
    ('360','Tham, Thám, Thàm, Thảm, Thăm',2),
    ('361','Thăm, Thắm, Thẳm, Thâm, Thậm, Thấm',2),
    ('362','Thấm, Thầm, Thẩm, Than',2),
    ('363','Than, Thán, Thàn, Thẩn, Thăn, Thằn, Thân',2),
    ('364','Thân',2),
    ('365','Thân, Thận, Thấn, Thần',2),
    ('366','Thần',2),
    ('367','Thần, Thẩn, Thang, Tháng',2),
    ('368','Tháng, Thảng, Thăng, Thặng, Thắng, Thằng',2),
    ('369','Thằng, Thẩng, Thâng, Thấng, Thanh',2),
    ('370','Thanh, Thạnh',2),
    ('371','Thạnh, Thánh',2),
    ('372','Thánh, Thành',2),
    ('373','Thành, Thảnh, Thao',2),
    ('374','Thao, Thạo, Tháo, Thào, Thảo',2),
    ('375','Thảo, Thạp, Tháp, Thắp',2),
    ('376','Thấp, Thập, Thát, Thắt',2),
    ('377','Thắt, Thất',2),
    ('378','Thất, Thật',2),
    ('379','Thật, Thau, Tháu, Thâu, Thấu',2),
    ('380','Thấu, Thuầu, Thẩu, The, Thè, Thé, Thẻ,',2),
    ('381','Thê, Thệ, Thế',2),
    ('382','Thế',2),
    ('383','Thế, Thề, Thể',2),
    ('384','Thể, Thề, Thếch, Thèm, Thêm',2),
    ('385','Thêm, Thềm, Then, Thẹn, Thển, Theo',2),
    ('386','Theo, Thẹo, Thèo, Thẻo, Thẹp, Thép, Thếp, Thét, Thệt',2),
    ('387','Thết, Thêu, Thều, Thểu, Thi',2),
    ('388','Thi, Thị',2),
    ('389','Thị, Thí',2),
    ('390','Thí, Thì, Thỉ',2),
    ('391','Thỉ, Thĩ, Thia, Thía, Thịch, Thích',2),
    ('392','Thích, Thiếc, Thiêm, Thiềm, Thiểm, Thiên',2),
    ('393','Thiên',2),
    ('394','Thiên, Thiện',2);
INSERT INTO db_dainam VALUES
    ('395','Thiện, Thiến, Thiền, Thiêng, Thiềng, Thiệp, Thiếp',2),
    ('396','Thiếp, Thiết, Thiệt',2),
    ('397','Thiệt, Thiêu, Thiệu, Thiếu',2),
    ('398','Thiếu, Thiều, Thiểu, Thím, Thìn, Thinh',2),
    ('399','Thinh, Thịnh, Thính, Thình, Thỉnh, Thíp, Thịt',2),
    ('400','Thịt, Thiu, Thỉu, Tho, Thọ',2),
    ('401','Thọ, Thó, Thò, Thỏ',2),
    ('402','Thô, Thộ, Thố, Thổ,',2),
    ('403','Thổ, Thơ',2),
    ('404','Thơ, Thợ, Thớ, Thờ',2),
    ('405','Thờ, Thở, Thoa, Thòa, Thỏa',2),
    ('406','Thóa, Thoại, Thoạn, Thoán, Thoàn, Thoáng, Thoát, Thoắt',2),
    ('407','Thoắt, Thoặt, Thóc, Thọc, Thốc, Thoen, Thoét, Thoi, Thói',2),
    ('408','Thói, Thòi, Thỏi, Thôi',2),
    ('409','Thôi, Thối, Thồi, Thổi, Thơi, Thới, Thởi, Thời, Thom',2),
    ('410','Thòm, Thóm, Thỏm, Thơm, Thớm, Thon, Thỏn, Thôn, Thốn, Thồn,',2),
    ('411','Thong, Thòng, Thõng, Thỏng, Thông',2),
    ('412','Thông, Thống, Thọp, Thóp, Thộp',2),
    ('413','Thọt, Thót, Thốt, Thợt, Thớt, Thu',2),
    ('414','Thu, Thụ, Thú, Thù',2),
    ('415','Thù, Thủ',2),
    ('416','Thủ, Thư, Thự, Thứ',2),
    ('417','Thứ, Thử, Thua',2),
    ('418','Thua, Thùa, Thưa, Thứa, Thừa',2),
    ('419','Thừa, Thửa, Thuận',2),
    ('420','Thuận, Thuấn, Thuần, Thuẫn',2),
    ('421','Thuẫn, Thuật, Thúc, Thục',2),
    ('422','Thục, Thức, Thực',2),
    ('423','Thực, Thuê, Thuế, Thui',2),
    ('424','Thui, Thúi, Thụi, Thùi, Thúy, Thùy, Thụy, Thủy, Thuyên',2),
    ('425','Thuyên, Thuyền, Thuyết, Thum, Thủm, Thun, Thùn, Thung, Thụng, Thúng',2),
    ('426','Thùng, Thũng, Thủng, Thưng, Thửng, Thuở, Thuộc, Thuốc',2),
    ('427','Thuốc',2),
    ('428','Thuốc, Thược, Thước',2),
    ('429','Thước, Thuội, Thuồn, Thuổn, Thuông, Thương',2),
    ('430','Thương, Thượng, Thướng, Thường',2),
    ('431','Thường, Thưởng, Thượt, Thụt, Thút',2),
    ('432','Thút, Ti, Tị, Tí, Tì',2),
    ('433','Tì, Tĩ, Tía, Tỉa, Tích',2),
    ('434','Tích, Tịch',2),
    ('435','Tịch, Tiệc, Tiếc, Tiêm, Tiệm, Tiếm, Tiềm, Tiên',2),
    ('436','Tiên, Tiện',2),
    ('437','Tiện, Tiến, Tiền',2),
    ('438','Tiền, Tiển, Tiếng',2),
    ('439','Tiếng, Tiệt, Tiết',2),
    ('440','Tiết, Tiêu',2),
    ('441','Tiêu, Tiếu, Tiều, Tiểu',2),
    ('442','Tiểu, Tim, Tím, Tịm, Tìm, Tin',2),
    ('443','Tim, Tín, Tìn, Tinh',2),
    ('444','Tinh, Tịnh, Tính',2),
    ('445','Tính, Tính, Tình',2),
    ('446','Tình, Tỉnh, Tĩnh, Tịt',2),
    ('447','Tịt, Tít, Tiu, Tìu, To, Tọ, Tó, Tò, Tỏ',2),
    ('448','Tỏ, Tô, Tộ, Tố, Tổ',2),
    ('449','Tổ, Tơ, Tợ',2),
    ('450','Tớ, Tờ, Tở, Toa, Tọa, Tóa, Tòa',2),
    ('451','Tòa, Tỏa, Toạc, Toác, Toại, Toái, Toan, Toán',2),
    ('452','Toán, Toát, Tọc, Tóc, Tộc, Tốc',2),
    ('453','Tốc, Toi, Tói, Tòi, Tỏi, Tôi, Tội',2),
    ('454','Tội, Tối, Tồi, Tơi',2),
    ('455','Tơi, Tời, Tới, Tom, Tóm, Tôm',2),
    ('456','Tôm, ton, Tòn, Tỏn, Tôn, Tốn, Tồn, Tổn',2),
    ('457','Tổn, Tơn, Tợn, Tớn, Tờn, Tởn, Tong, Tòng, Tông, Tống',2),
    ('458','Tống, Tổng, Tóp, Tốp, Tót, Tọt, Tột',2),
    ('459','Tột, Tốt, Tra',2),
    ('460','Tra, Trá, Trà, Trả',2),
    ('461','Trả, Trác, Trác, Trạc, Trắc,',2),
    ('462','Trắc, Trặc, Trách, Trạch, Trai',2),
    ('463','Trai, Trại, Trái',2),
    ('464','Trái, Trải, Trạy, Tráy',2),
    ('465','Trảy, Trây, Trầy, Trẩy, Trạm, Trám, Tràm',2),
    ('466','Tràm, Trảm, Trăm, Trắm, Trằm, Trâm, Trậm, Trầm',2),
    ('467','Trầm, Trấm, Trẩm, Trẫm, Tran, Trán, Tràn, Trản, Trăn, Trắn',2),
    ('468','Trằn, Trần, Trân, Trận, Trấn',2),
    ('469','Trấn, Trần, Trẫn, Trang',2),
    ('470','Trang, Trạng, Tráng, Tràng',2),
    ('471','Tràng, Trăng, Trắng',2),
    ('472','Trắng, Trằng, Trảng, Trâng, Trẫng, Tranh',2),
    ('473','Tranh, Trạnh, Tránh, Trành, Trao, Trạo, Tráo',2),
    ('474','Trào, Trảo, Trắp, Trấp, Trập, Trát, Trạt, Trất, Trật',2),
    ('475','Trật, Trau, Tràu, Trảu, Trâu, Trấu, Trầu',2),
    ('476','Trầu, Tre, Trẹ, Tré, Trẻ',2),
    ('477','Trẽ, Trê, Trệ, Trề, Trễ, Trệch, Trèm',2),
    ('478','Trẹm, Trẻn, Trên, Trênh, Treo',2),
    ('479','Trẹo, Tréo, Trèo, Trẽo, Trẹt, Trét, Trết',2),
    ('480','Trết, Trệt, Trêu, Trệu, Trếu, Trều, Tri',2),
    ('481','Tri, Trị, Trí',2),
    ('482','Trí, Trì, Trĩ, Tría, Trỉa, Trìa, Trịch',2),
    ('483','Trích, Triêm, Triến, Triền, Triển, Triêng, Triệng, Triềng, Tri, Triệt, Triêu, Triệu',2),
    ('484','Triệu, Triều, Trinh, Trịnh, Trình, Trịt, Trít',2),
    ('485','Trịu, Tríu, Tro, Trọ, Trò, Trỏ, Trộ, Trổ',2),
    ('486','Trỗ, Trồ, Trơ, Trớ, Trợ, Trờ, Trở',2),
    ('487','Trở, Troán, Tróc, Trọc, Trốc',2),
    ('488','Trọi, Trói, Trỏi, Trôi, Trội, Trối, Trồi',2),
    ('489','Trồi, Trổi, Trơi, Trới, Trời',2),
    ('490','Trời, Trom, Tròm, Trồm, Trôm, Trộm, Trợn, Trờm, Tron, Trọn',2),
    ('491','Trọn, Tròn, Trỏn, Trôn, Trộn, Trốn, Trơn, Trợn',2),
    ('492','Trợn, Trớn, Trong, Trọng',2),
    ('493','Trọng, Tróng, Tròng, Trỏng, Trông, Trộng, Trống',2),
    ('494','Trống, Trồng',2),
    ('495','Trồng, Trổng, Trớp, Trớt, Trợt, Trợu, Tru, Trụ',2),
    ('496','Trụ, Trú, Trù, TRủ, Trư, Trự, Trừ',2),
    ('497','Trử, Trưa, Trựa, Truất, Truật, Trúc, Trục, Trực',2),
    ('498','Trực, Trui, Trụi, Trùi, Truy, Trụy, Truyện, Truyền',2),
    ('499','Truyền, Trụm, Trúm, Trùm, Trũm, Trun, Trùn, Trung',2),
    ('500','Trung, Trụng, Trúng, Trùng',2),
    ('501','Trùng, Trũng, Trưng, Trứng, Trừng, Trước',2),
    ('502','Trước, Trược, Trườn, Truông, Truồng, Trương',2),
    ('503','Trương, Trượng, Trướng, Trường',2),
    ('504','Trường, Trưởng, Truột, Trụt, Trút',2),
    ('505','Trút, Trứu, Trừu, Trửu, Tu, Tụ',2),
    ('506','Tụ, Tú, Tù, Tủ',2),
    ('507','Tủ, Tư',2),
    ('508','Tư, Tự',2),
    ('509','Tự, Tứ, Từ',2),
    ('510','Từ, Tử',2),
    ('511','Tử',2),
    ('512','Tử, Tua, Túa, Tùa, Tủa, Tưa, Tựa, Tửa, Tuân, Tuấn, Tuận, Tuần',2),
    ('513','Tuần, Tuất, Túc',2),
    ('514','Túc, Tục, Tức',2),
    ('515','Tức, Tuệ, Tuế, Tui, Tụi, Túi, Tủi, Tuiến',2),
    ('516','Tuiến, Tuy, Tụy, Tủy, Tuyên, Tuyến, Tuyền, Tuyển',2),
    ('517','Tuyển, Tuyết, Tuyệt, Tum, Túm, Tùm, Tun, Tung',2),
    ('518','Tung, Tụng, Túng, Tùng',2),
    ('519','Tùng, Tưng, Từng, Tửng, Tược, Tước, Tuổi',2),
    ('520','Tuổi, Tươi, Tưới, Tưởi, Tuồm, Tưỡm, Tuôn, Tươn',2),
    ('521','Tươn, Tuồng, Tương, Tượng',2),
    ('522','Tượng, Tướng, Tường',2),
    ('523','Tường, Tưởng, Tuột, Tuốt, Tượt, Tướt, Tựu',2),
    ('524','Tựu, Tửu, U, Ụ',2),
    ('525','Ú, Ù, Ủ, Ư, Ứ, Ừ, Uạ, Úa, Ưa',2),
    ('526','Ứa, Uất, Ục, Úc, Ực, Ức, Úe; Úê, Uí, Úi, Ủi',2),
    ('527','Ui, Ũi, Uy, Úy, Ửy, Uyên, Uyền, Uinh, Uĩnh, Um, Úm, Ùm',2),
    ('528','Ủm, Un, Ún, Ùn, Ủn, Ung, Ùng, Ủng, Ưng, Ứng',2),
    ('529','Ứng, Ưng, Ước, Ưởi, Ươm, Ướm, Uốn, Ươn; Uống',2),
    ('530','Uống, Uổng, Ương, Ướt, Úp; Ụp, Út',2),
    ('531','Út, Ụt, Ưu',2),
    ('532','Va, Vạ, Vá',2),
    ('533','Vá, Và, Vả, Vã',2),
    ('534','Vã, Vác, Vạc, Vắc, Vấc, Vậc, Vách, Vạch',2),
    ('535','Vạch, Vai, Vái, Vài, Vải',2),
    ('536','Vải, Vãi, Vay, Vạy, Váy, Vảy',2),
    ('537','Vảy, Vây, Vậy, Vấy',2),
    ('538','Vấy, Vầy, Vẫy, Vảm, Van, Vạn',2),
    ('539','Vạn, Ván, Vàn, Vãn, Văn, Vận, Vẳn, Vẳn, Vân',2),
    ('540','Vần, Vận, Vấn, Vần, Vẩn, Vẫn',2),
    ('541','Vẫn, Vang, Vạng, Váng, Vàng',2),
    ('542','Vãng, Văng, Vắng, Vàng, Vãng, Vâng, Vầng',2),
    ('543','Vầng, Vanh, Vánh, Vành, Vảnh, Vào, Vập, Vấp, Vạt',2),
    ('544','Vạt, Vát, Vặt, Vất, Vật',2),
    ('545','Vật, Vảu, Vấu, Ve, Vé, Vè',2),
    ('546','Vè, Vẻ, Vẽ, Vẹ Vê, Vệ, Vế, Về',2),
    ('547','Về, Vể, Vếch, Vệch, Vẹm, Ven, Vẹn, Vén, Vèn, Vẻn, Vên',2),
    ('548','Vên, Vện, Vênh, Vếnh, Veo, Vẹo, Vèo, Véo, Vẻo, Vét, Vẹt, Vêu',2),
    ('549','Vêu, Vếu, Vi, Vị',2),
    ('550','Vị, Ví, Vì, Vỉ',2),
    ('551','Vĩ, Vía, Vỉa, Vích, Vịch, Việc',2),
    ('552','Việc, Viên, Viện, Viền, Viễn, Viếng',2),
    ('553','Viếng, Viết, Việt, Vịm, Vin, Vịn, Vìn, Vinh, Vịnh',2),
    ('554','Vịnh, Vính, Vĩnh, Vịt, Vít, Viu, Vo, Vọ, Vó, Vò',2),
    ('555','Vò, Vỏ, Võ, Vô',2),
    ('556','Vô, Vố, Vồ, Vổ, Vỗ, Vơ, Vợ, Vớ, Vở',2),
    ('557','Vở, Vỡ, Vọc, Vóc, Vốc, Voi',2),
    ('558','Voi, Vọi, Vói, Vòi, vỏi, Vôi, Vội, Vơi, Vợi, Với',2),
    ('559','Vời, Vởi, Vom, Vòm, Von, Vỏn, Vốn, Vồn, Vờn, Vởn, Vong',2),
    ('560','Vong, Vọng, Vóng, Vòng, Võng, Vông, Vồng',2),
    ('561','Vồng, Vổng, Vọp, Vót, Vọt, Vớt, Vợt, Vu, Vụ',2),
    ('562','Vụ, Vú, Vù, Vũ, Vua',2),
    ('563','Vua, Vùa, Vựa, Vứa, Vừa, Vữa, Vục, Vúc',2),
    ('564','Vức, Vực, Vui, Vùi, Vũm, Vun, Vụn, Vung',2),
    ('565','Vung, Vụng, Vùng, Vũng, Vưng, Vựng, Vừng, Vửng, Vững',2),
    ('566','Vững, Vược, Vuối, Vuội, Vươn, Vượn, Vướn, Vuông, Vương',2),
    ('567','Vương, Vượng, Vướng, Vưởng, Vuốt, Vuột, Vượt, Vụt',2),
    ('568','Vút, Vưu, Xa',2),
    ('569','Xa, Xạ, Xá, Xà, Xả',2),
    ('570','Xã, Xạc, Xác, Xấc, Xách',2),
    ('571','Xách, Xạch, Xai, Xái, Xài, Xay, Xáy, Xạy, Xảy, Xây',2),
    ('572','Xây, Xầy, Xam, Xạm, Xám, Xàm, Xảm, Xăm',2),
    ('573','Xăm, Xắm, Xâm, Xấm, Xầm, Xẩm, Xan, Xán, Xăn, Xắn, Xẳn, Xang, Xàng',2),
    ('574','Xàng, Xăng, Xằng, Xảng, Xanh, Xánh, Xảnh, Xao',2),
    ('575','Xao, Xạo, Xáo, Xào, Xảo, Xạp, Xáp, Xắp, Xấp',2),
    ('576','Xấp, Xát, Xạu, Xáu, Xàu, Xâu, Xấu',2),
    ('577','Xấu, Xe, Xẹ, Xé, Xè, Xẻ',2),
    ('578','Xẻ, Xê, Xệ, Xế, Xề, Xể, Xếch, Xệch, Xem, Xen, Xén, Xèn, Xẻn',2),
    ('579','Xên, Xện, Xển, Xênh, Xeo, Xẹo, Xéo, Xèo, Xẻo, Xẽo, Xẹp, Xép, Xếp',2),
    ('580','Xếp, Xẹt, Xét, Xệu, Xếu, Xều, Xi, Xị, Xí',2),
    ('581','Xí, Xì, Xỉ, Xía, Xỉa, Xịch, Xích',2),
    ('582','Xích, Xiêm, Xiểm, Xiên, Xiển, Xiềng, Xiểng, Xiết, Xiêu',2),
    ('583','Xin, Xỉn, Xinh, Xính, Xình, Xỉnh, Xịt, Xít, Xíu, Xìu, Xỉu, Xo, Xó',2),
    ('584','Xó, Xò, Xỏ, Xõ, Xô, Xố, Xồ, Xổ, Xơ',2),
    ('585','Xơ, Xớ, Xờ, Xoa, Xọa, Xóa, Xòa, Xoác, Xoai, Xoái, Xoài, Xoay, Xoáy',2),
    ('586','Xoáy, Xoan, Xoắn, Xoang, Xoáng, Xoàng, Xoắt, Xọc, Xóc, Xộc, Xốc',2),
    ('587','Xốc, Xoi, Xói, Xôi, Xối, Xổi, Xơi, Xới, Xởi',2),
    ('588','Xom, Xóm, Xỏm, Xôm, Xồm, Xổm, Xơm, Xớm, Xờm, Xòn, Xỏn, Xôn, Xộn, Xốn',2),
    ('589','Xổn, Xơn, Xớn, Xởn, Xong, Xóng, Xõng, Xông, Xộng, Xổng, Xống, Xóp',2),
    ('590','Xóp, Xộp, Xốp, Xợp, Xọt, Xót, Xốt, Xợt, Xớt, Xu, Xụ, Xú, Xù',2),
    ('591','Xù, Xủ, Xự, Xứ, Xừ, Xử, Xua, Xưa',2),
    ('592','Xuân, Xuẩn, Xuất, Xục, Xúc, Xức',2),
    ('593','Xuê, Xuể, Xui, Xúi, Xụi, Xùi, Xủi, Xuy, Xuyên, Xuyến',2),
    ('594','Xuýt, Xúm, Xủn, Xung, Xúng, Xưng, Xứng, X72ng, Xửng, Xược',2),
    ('595','Xước, Xuôi, Xuội, Xười, Xuông, Xuống, Xuồng',2),
    ('596','Xuổng, Xương, Xướng, Xưởng, Xúp, Xụt, Xút',2);
